module.exports = [
  {
    id: "ag-farm",
    name: "Farm / Ranch",
    sector: "agriculture",
    size: ["solo", "small", "medium"],
    description: "Farm or ranch operation producing crops, livestock, or specialty agricultural products",
    departments: [
      { domain: "General", name: "Production", capabilities: ["crop-management", "livestock-care", "harvest-planning", "irrigation", "soil-management"] },
      { domain: "General", name: "Equipment", capabilities: ["maintenance", "procurement", "scheduling", "repairs"] },
      { domain: "Marketing", name: "Sales", capabilities: ["direct-sales", "wholesale", "farmers-market", "CSA-programs", "buyer-relations"] },
      { domain: "Legal", name: "Compliance", capabilities: ["USDA-reporting", "EPA-compliance", "certifications", "record-keeping"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "crop-insurance", "loan-management", "tax-planning", "budgeting"] },
    ],
    governance: {
      compliance: ["USDA", "EPA", "OSHA", "state agriculture regulations"],
      riskSignals: ["FOOD_SAFETY", "REGULATED_SUBSTANCE"],
      additionalDomains: ["Agriculture", "Operations"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["farm", "ranch", "agriculture", "farming", "crops", "livestock", "dairy", "organic-farm", "vineyard", "orchard"],
  },
  {
    id: "ag-cooperative",
    name: "Agricultural Cooperative",
    sector: "agriculture",
    size: ["medium", "large"],
    description: "Agricultural cooperative providing shared services and market access for member farmers",
    departments: [
      { domain: "General", name: "Operations", capabilities: ["grain-handling", "storage", "processing", "logistics", "quality-control"] },
      { domain: "General", name: "Member Services", capabilities: ["member-support", "input-sales", "agronomy-advice", "communications"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["commodity-marketing", "pricing", "contracts", "market-analysis"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "patronage-dividends", "equity-management", "budgeting"] },
      { domain: "Legal", name: "Compliance", capabilities: ["USDA-regulations", "Capper-Volstead", "reporting", "governance"] },
    ],
    governance: {
      compliance: ["Capper-Volstead Act", "USDA regulations"],
      riskSignals: ["FOOD_SAFETY"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["cooperative", "co-op", "agricultural-cooperative", "grain-elevator", "farm-co-op", "commodity", "member-owned", "agricultural-marketing"],
  },
  {
    id: "ag-agtech",
    name: "AgTech / Precision Agriculture",
    sector: "agriculture",
    size: ["small", "medium"],
    description: "Agricultural technology company developing precision farming tools and solutions",
    departments: [
      { domain: "General", name: "Engineering", capabilities: ["software-development", "hardware-design", "IoT-sensors", "data-analytics"] },
      { domain: "General", name: "Product", capabilities: ["product-management", "UX-design", "roadmap", "customer-feedback"] },
      { domain: "General", name: "Field Operations", capabilities: ["deployment", "field-testing", "customer-success", "training"] },
      { domain: "Marketing", name: "Sales", capabilities: ["business-development", "demos", "partnerships", "dealer-network"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "fundraising", "budgeting", "revenue-tracking"] },
    ],
    governance: {
      compliance: ["USDA", "EPA"],
      riskSignals: ["TRADE_SECRET"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["agtech", "precision-agriculture", "farm-technology", "smart-farming", "agricultural-technology", "drone-agriculture", "farm-data", "crop-analytics"],
  },
];
