module.exports = [
  {
    id: "auto-dealer",
    name: "Car Dealership",
    sector: "automotive",
    size: ["small", "medium", "large"],
    description: "New or used car dealership with sales, financing, and service departments",
    departments: [
      { domain: "Marketing", name: "Sales", capabilities: ["vehicle-sales", "lead-management", "test-drives", "customer-follow-up", "trade-ins"] },
      { domain: "Finance", name: "F&I", capabilities: ["financing", "insurance-products", "deal-structuring", "compliance", "credit-applications"] },
      { domain: "General", name: "Service", capabilities: ["maintenance", "repairs", "warranty-work", "scheduling", "inspections"] },
      { domain: "General", name: "Parts", capabilities: ["parts-inventory", "ordering", "wholesale", "accessories"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["advertising", "digital-marketing", "promotions", "inventory-merchandising"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "training", "benefits", "compliance"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "deal-accounting", "floor-plan", "payroll", "reporting"] },
    ],
    governance: {
      compliance: ["FTC regulations", "state dealer licensing", "TILA", "fair lending laws"],
      riskSignals: ["FINANCIAL", "PII"],
      additionalDomains: [],
      hitlDefaults: { "advertising-claims": "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["car-dealership", "auto-dealer", "car-sales", "vehicle-sales", "dealership", "used-cars", "new-cars", "automotive-sales", "car-lot"],
  },
  {
    id: "auto-repair",
    name: "Auto Repair / Service",
    sector: "automotive",
    size: ["solo", "small", "medium"],
    description: "Independent auto repair shop or service center providing vehicle maintenance and repair",
    departments: [
      { domain: "General", name: "Service", capabilities: ["diagnostics", "repairs", "maintenance", "inspections", "estimates"] },
      { domain: "General", name: "Parts", capabilities: ["parts-ordering", "inventory", "returns", "vendor-relations"] },
      { domain: "General", name: "Front Office", capabilities: ["scheduling", "customer-communication", "invoicing", "check-in-out"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "invoicing", "payroll", "budgeting"] },
    ],
    governance: {
      compliance: ["state licensing", "EPA regulations", "OSHA"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["auto-repair", "mechanic", "car-repair", "auto-service", "garage", "body-shop", "oil-change", "brake-shop", "tire-shop"],
  },
  {
    id: "auto-fleet",
    name: "Fleet Sales / Leasing",
    sector: "automotive",
    size: ["medium", "large"],
    description: "Fleet vehicle sales and leasing operation serving business and government clients",
    departments: [
      { domain: "Marketing", name: "Sales", capabilities: ["fleet-sales", "proposals", "RFP-responses", "client-relations", "negotiations"] },
      { domain: "General", name: "Fleet Management", capabilities: ["vehicle-allocation", "lifecycle-management", "remarketing", "logistics"] },
      { domain: "Finance", name: "Finance", capabilities: ["lease-accounting", "deal-structuring", "invoicing", "budgeting", "residual-analysis"] },
      { domain: "General", name: "Operations", capabilities: ["delivery-coordination", "titling-registration", "vendor-management"] },
    ],
    governance: {
      compliance: ["UCC", "state fleet regulations"],
      riskSignals: ["FINANCIAL"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["fleet-sales", "fleet-leasing", "commercial-vehicles", "fleet-dealer", "vehicle-leasing", "corporate-fleet", "fleet-acquisition"],
  },
];
