module.exports = [
  {
    id: "care-childcare",
    name: "Childcare / Daycare",
    sector: "care",
    size: ["small", "medium"],
    description: "Childcare center or daycare facility providing early childhood care and education",
    departments: [
      { domain: "General", name: "Care Services", capabilities: ["curriculum", "classroom-management", "child-development", "activities"] },
      { domain: "General", name: "Administration", capabilities: ["enrollment", "scheduling", "parent-communication", "records"] },
      { domain: "Legal", name: "Compliance", capabilities: ["licensing", "background-checks", "inspections", "CCDF-reporting"] },
      { domain: "Finance", name: "Finance", capabilities: ["tuition-billing", "accounting", "subsidy-management", "budgeting"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "credentialing", "training", "ratios-compliance"] },
      { domain: "Comms", name: "Family Relations", capabilities: ["parent-engagement", "newsletters", "conferences", "feedback"] },
    ],
    governance: {
      compliance: ["state childcare licensing", "CCDF", "background check requirements", "COPPA"],
      riskSignals: ["MINOR_DATA", "PII"],
      additionalDomains: ["Education"],
      hitlDefaults: { "abuse-neglect": "ESCALATE" },
      localOnlyDomains: ["care-records"],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["childcare", "daycare", "preschool", "early-childhood", "child-development", "nursery", "after-school", "head-start", "infant-care", "toddler"],
  },
  {
    id: "care-seniorliving",
    name: "Senior Living / Nursing Home",
    sector: "care",
    size: ["medium", "large"],
    description: "Senior living community or nursing home providing residential care for elderly adults",
    departments: [
      { domain: "General", name: "Care Services", capabilities: ["personal-care", "activities", "dining", "transportation", "memory-care"] },
      { domain: "Healthcare", name: "Nursing", capabilities: ["medication-management", "care-plans", "assessments", "clinical-records"] },
      { domain: "General", name: "Administration", capabilities: ["admissions", "scheduling", "records", "family-communication"] },
      { domain: "Legal", name: "Compliance", capabilities: ["CMS-surveys", "state-licensing", "incident-reporting", "quality-measures"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "Medicaid-Medicare", "accounting", "budgeting"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "credentialing", "training", "scheduling", "retention"] },
      { domain: "Comms", name: "Resident Relations", capabilities: ["family-engagement", "activities-calendar", "feedback", "advocacy"] },
    ],
    governance: {
      compliance: ["CMS regulations", "state licensing", "HIPAA", "elder abuse reporting"],
      riskSignals: ["PHI", "MINOR_DATA"],
      additionalDomains: [],
      hitlDefaults: { "abuse-neglect": "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["senior-living", "nursing-home", "assisted-living", "elder-care", "memory-care", "retirement-community", "long-term-care", "skilled-nursing", "independent-living"],
  },
  {
    id: "care-homecare",
    name: "Home Health / Personal Care",
    sector: "care",
    size: ["small", "medium"],
    description: "Home health agency or personal care service providing in-home care for patients",
    departments: [
      { domain: "Healthcare", name: "Care Services", capabilities: ["home-visits", "care-plans", "patient-assessments", "medication-management"] },
      { domain: "General", name: "Scheduling", capabilities: ["caregiver-assignment", "visit-scheduling", "route-optimization", "coverage"] },
      { domain: "Legal", name: "Compliance", capabilities: ["state-licensing", "HIPAA", "Medicaid-billing", "documentation"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "insurance-claims", "payroll", "budgeting"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "credentialing", "training", "background-checks"] },
    ],
    governance: {
      compliance: ["state licensing", "HIPAA", "Medicaid regulations"],
      riskSignals: ["PHI"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: ["Healthcare"],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["home-health", "home-care", "personal-care", "in-home-care", "visiting-nurse", "home-health-aide", "caregiver", "hospice", "private-duty"],
  },
];
