module.exports = [
  {
    id: "construction-gc",
    name: "General Contractor",
    sector: "construction",
    size: ["small", "medium", "large"],
    description: "General contractor handling commercial or residential construction projects",
    departments: [
      { domain: "ProjectMgmt", name: "Project Management", capabilities: ["scheduling", "budgeting", "submittals", "rfi-management", "change-orders", "closeout"] },
      { domain: "Estimating", name: "Estimating & Preconstruction", capabilities: ["takeoffs", "bid-preparation", "subcontractor-selection", "value-engineering", "proposals"] },
      { domain: "FieldOperations", name: "Field Operations", capabilities: ["site-supervision", "quality-control", "subcontractor-coordination", "inspections", "punch-lists"] },
      { domain: "Safety", name: "Safety", capabilities: ["safety-plans", "osha-compliance", "incident-investigation", "training", "toolbox-talks", "site-audits"] },
      { domain: "Finance", name: "Finance", capabilities: ["job-costing", "accounts-payable", "accounts-receivable", "payroll", "bonding", "insurance"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "training", "labor-relations", "apprenticeships"] },
    ],
    governance: {
      compliance: ["OSHA", "State Contractor Licensing", "Bonding Requirements", "Building Codes", "Prevailing Wage"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: ["Construction", "WorkplaceSafety"],
      hitlDefaults: { Safety: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["general contractor", "construction company", "builder", "GC", "construction firm", "commercial construction", "residential construction", "building contractor", "construction management"],
  },
  {
    id: "construction-trade",
    name: "Specialty Trade Contractor",
    sector: "construction",
    size: ["solo", "small", "medium"],
    description: "Specialty trade contractor such as electrical, plumbing, HVAC, or roofing",
    departments: [
      { domain: "Operations", name: "Operations", capabilities: ["job-scheduling", "dispatching", "service-calls", "installations", "project-execution"] },
      { domain: "Estimating", name: "Estimating", capabilities: ["proposals", "takeoffs", "material-pricing", "bid-coordination"] },
      { domain: "Safety", name: "Safety", capabilities: ["safety-plans", "osha-compliance", "ppe", "incident-reporting", "training"] },
      { domain: "Finance", name: "Finance", capabilities: ["invoicing", "job-costing", "payroll", "bookkeeping", "bonding"] },
    ],
    governance: {
      compliance: ["OSHA", "State Trade Licensing", "Building Codes", "Bonding"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: ["Construction", "WorkplaceSafety"],
      hitlDefaults: { Safety: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["electrician", "plumber", "HVAC", "plumbing", "electrical contractor", "roofing", "painting contractor", "masonry", "concrete", "drywall", "specialty trade", "subcontractor"],
  },
  {
    id: "construction-architecture",
    name: "Architecture Firm",
    sector: "construction",
    size: ["small", "medium"],
    description: "Architecture or architectural design firm",
    departments: [
      { domain: "Design", name: "Design", capabilities: ["schematic-design", "design-development", "construction-documents", "3d-modeling", "sustainability"] },
      { domain: "ProjectMgmt", name: "Project Management", capabilities: ["project-coordination", "client-liaison", "construction-administration", "scheduling", "budgets"] },
      { domain: "BusinessDev", name: "Business Development", capabilities: ["proposals", "rfq-responses", "client-relations", "marketing", "competitions"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "project-accounting", "bookkeeping", "payroll", "budgeting"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "licensing-support", "professional-development"] },
    ],
    governance: {
      compliance: ["State Architecture Licensing", "ADA", "Building Codes", "International Building Code", "Professional Liability"],
      riskSignals: ["TRADE_SECRET"],
      additionalDomains: ["Construction", "Design"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["architecture", "architect", "architecture firm", "architectural design", "building design", "AIA", "design firm", "architectural services", "landscape architecture"],
  },
  {
    id: "construction-engineering",
    name: "Engineering Firm",
    sector: "construction",
    size: ["small", "medium", "large"],
    description: "Civil, structural, mechanical, or environmental engineering firm",
    departments: [
      { domain: "Engineering", name: "Engineering", capabilities: ["civil", "structural", "mechanical", "environmental", "geotechnical", "surveying", "analysis"] },
      { domain: "ProjectMgmt", name: "Project Management", capabilities: ["project-coordination", "client-liaison", "construction-oversight", "scheduling", "budgets"] },
      { domain: "Quality", name: "Quality & QA/QC", capabilities: ["peer-review", "field-inspection", "testing", "standards-compliance", "documentation"] },
      { domain: "BusinessDev", name: "Business Development", capabilities: ["proposals", "rfq-responses", "client-relations", "marketing", "government-contracting"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "project-accounting", "bookkeeping", "payroll", "budgeting"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "pe-licensing-support", "professional-development"] },
    ],
    governance: {
      compliance: ["PE Licensing", "Safety Regulations", "Environmental Regulations", "Professional Liability", "Building Codes"],
      riskSignals: ["SAFETY_INCIDENT", "TRADE_SECRET"],
      additionalDomains: ["Construction", "Engineering"],
      hitlDefaults: { Quality: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["engineering firm", "civil engineering", "structural engineering", "mechanical engineering", "environmental engineering", "PE", "engineer", "geotechnical", "surveying", "MEP"],
  },
];
