module.exports = [
  {
    id: "edu-k12",
    name: "K-12 School/District",
    sector: "education",
    size: ["small", "medium", "large"],
    description: "K-12 school or district with student privacy protections and academic program support",
    departments: [
      { domain: "Academics", name: "Academics & Curriculum", capabilities: ["curriculum-design", "assessment", "instructional-support", "special-education", "gifted-programs"] },
      { domain: "StudentServices", name: "Student Services", capabilities: ["counseling", "student-records", "discipline", "health-services", "transportation"] },
      { domain: "Admissions", name: "Enrollment & Admissions", capabilities: ["registration", "transfers", "boundary-management", "lottery"] },
      { domain: "IT", name: "Information Technology", capabilities: ["infrastructure", "student-devices", "ed-tech", "data-privacy", "helpdesk"] },
      { domain: "Facilities", name: "Facilities & Operations", capabilities: ["maintenance", "custodial", "food-services", "safety", "construction"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "certification-tracking", "benefits", "labor-relations"] },
      { domain: "Finance", name: "Finance & Budget", capabilities: ["budgeting", "procurement", "grants", "payroll", "levy-management"] },
    ],
    governance: {
      compliance: ["FERPA", "COPPA", "Title IX", "IDEA", "ADA", "Section 504"],
      riskSignals: ["FERPA_DATA", "MINOR_DATA", "PII"],
      additionalDomains: ["Education", "MinorProtection"],
      hitlDefaults: { StudentServices: "ESCALATE" },
      localOnlyDomains: ["Education"],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["school", "school district", "k-12", "elementary", "middle school", "high school", "superintendent", "principal", "public school", "charter school", "education"],
  },
  {
    id: "edu-college",
    name: "Community College",
    sector: "education",
    size: ["medium", "large"],
    description: "Community or junior college with workforce development and transfer programs",
    departments: [
      { domain: "Academics", name: "Academic Affairs", capabilities: ["curriculum", "faculty-support", "accreditation", "workforce-programs", "continuing-education"] },
      { domain: "StudentServices", name: "Student Services", capabilities: ["advising", "counseling", "disability-services", "student-life", "records"] },
      { domain: "Admissions", name: "Admissions & Enrollment", capabilities: ["applications", "registration", "orientation", "recruitment", "dual-enrollment"] },
      { domain: "FinancialAid", name: "Financial Aid", capabilities: ["fafsa-processing", "scholarships", "grants", "work-study", "veteran-benefits"] },
      { domain: "IT", name: "Information Technology", capabilities: ["infrastructure", "lms", "cybersecurity", "helpdesk", "data-analytics"] },
      { domain: "Library", name: "Library & Learning Resources", capabilities: ["collections", "tutoring", "research-support", "media-services"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "labor-relations", "professional-development"] },
      { domain: "Finance", name: "Finance & Administration", capabilities: ["budgeting", "procurement", "facilities", "payroll", "grants"] },
    ],
    governance: {
      compliance: ["FERPA", "Title IX", "Clery Act", "ADA", "Section 504"],
      riskSignals: ["FERPA_DATA", "PII"],
      additionalDomains: ["Education"],
      hitlDefaults: { StudentServices: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["community college", "junior college", "two-year college", "technical college", "vocational college", "associate degree", "workforce development"],
  },
  {
    id: "edu-university",
    name: "University",
    sector: "education",
    size: ["large", "enterprise"],
    description: "Four-year university or research institution with comprehensive academic and research programs",
    departments: [
      { domain: "Academics", name: "Academic Affairs", capabilities: ["curriculum", "faculty-support", "accreditation", "graduate-programs", "provost-office"] },
      { domain: "StudentServices", name: "Student Affairs", capabilities: ["advising", "counseling", "housing", "student-life", "records", "career-services"] },
      { domain: "Admissions", name: "Admissions", capabilities: ["undergraduate-admissions", "graduate-admissions", "international-admissions", "recruitment"] },
      { domain: "FinancialAid", name: "Financial Aid", capabilities: ["fafsa-processing", "scholarships", "grants", "loans", "work-study"] },
      { domain: "IT", name: "Information Technology", capabilities: ["infrastructure", "research-computing", "cybersecurity", "lms", "data-governance"] },
      { domain: "Library", name: "Library & Archives", capabilities: ["collections", "research-support", "special-collections", "digital-scholarship"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "labor-relations", "faculty-affairs"] },
      { domain: "Finance", name: "Finance & Administration", capabilities: ["budgeting", "procurement", "endowment", "grants-accounting", "facilities"] },
      { domain: "Research", name: "Research & Sponsored Programs", capabilities: ["grant-management", "irb", "tech-transfer", "research-compliance", "core-facilities"] },
      { domain: "Athletics", name: "Athletics", capabilities: ["ncaa-compliance", "team-operations", "recruiting", "facilities", "media-relations"] },
    ],
    governance: {
      compliance: ["FERPA", "Title IX", "Clery Act", "IRB", "ADA", "Section 504", "Export Controls"],
      riskSignals: ["FERPA_DATA", "PII"],
      additionalDomains: ["Education", "ClinicalResearch"],
      hitlDefaults: { StudentServices: "ESCALATE", Research: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["university", "college", "four-year", "research university", "higher education", "campus", "provost", "dean", "undergraduate", "graduate", "doctoral"],
  },
  {
    id: "edu-trade",
    name: "Trade/Vocational School",
    sector: "education",
    size: ["small", "medium"],
    description: "Trade or vocational school focused on hands-on career training",
    departments: [
      { domain: "Programs", name: "Programs & Instruction", capabilities: ["curriculum", "instructor-support", "certifications", "apprenticeships", "lab-management"] },
      { domain: "StudentServices", name: "Student Services", capabilities: ["advising", "career-placement", "records", "disability-services"] },
      { domain: "Admissions", name: "Admissions & Enrollment", capabilities: ["applications", "registration", "recruitment", "orientation"] },
      { domain: "Finance", name: "Finance & Administration", capabilities: ["budgeting", "tuition", "financial-aid", "procurement"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "compliance"] },
    ],
    governance: {
      compliance: ["FERPA", "ADA", "Gainful Employment"],
      riskSignals: ["FERPA_DATA", "PII"],
      additionalDomains: ["Education"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["trade school", "vocational", "technical school", "career training", "apprenticeship", "certification program", "skilled trades", "CDL", "welding", "cosmetology", "HVAC training"],
  },
  {
    id: "edu-online",
    name: "Online Education Platform",
    sector: "education",
    size: ["small", "medium", "large"],
    description: "Online or hybrid education provider with digital-first operations",
    departments: [
      { domain: "Content", name: "Content & Curriculum", capabilities: ["course-design", "instructional-design", "video-production", "assessment-design", "accessibility"] },
      { domain: "StudentSupport", name: "Student Support", capabilities: ["technical-support", "advising", "tutoring", "accessibility-services", "records"] },
      { domain: "IT", name: "Information Technology", capabilities: ["lms-management", "platform-engineering", "cybersecurity", "data-analytics", "integrations"] },
      { domain: "Marketing", name: "Marketing & Enrollment", capabilities: ["digital-marketing", "enrollment-campaigns", "partnerships", "brand", "seo"] },
      { domain: "Finance", name: "Finance & Operations", capabilities: ["budgeting", "tuition", "subscriptions", "vendor-management", "payroll"] },
    ],
    governance: {
      compliance: ["FERPA", "COPPA", "ADA", "WCAG", "State Authorization"],
      riskSignals: ["FERPA_DATA", "MINOR_DATA", "PII"],
      additionalDomains: ["Education", "DigitalPrivacy"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["online education", "e-learning", "edtech", "online school", "virtual academy", "distance learning", "MOOC", "online courses", "learning platform", "LMS"],
  },
];
