module.exports = [
  {
    id: "energy-utility",
    name: "Utility Provider (Electric / Gas / Water)",
    sector: "energy",
    size: ["large", "enterprise"],
    description: "Electric, gas, or water utility providing essential services to residential and commercial customers",
    departments: [
      { domain: "General", name: "Operations", capabilities: ["grid-management", "distribution", "generation", "outage-response", "metering"] },
      { domain: "General", name: "Engineering", capabilities: ["infrastructure-design", "capital-projects", "reliability", "innovation"] },
      { domain: "General", name: "Customer Service", capabilities: ["billing-support", "service-requests", "complaints", "programs"] },
      { domain: "Legal", name: "Regulatory", capabilities: ["rate-cases", "PUC-filings", "compliance-reporting", "policy-analysis"] },
      { domain: "General", name: "Safety", capabilities: ["safety-programs", "emergency-response", "inspections", "training"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "rate-design", "budgeting", "capital-planning", "revenue-assurance"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "labor-relations", "training", "benefits", "workforce-planning"] },
    ],
    governance: {
      compliance: ["PUC/PSC regulations", "NERC standards", "EPA", "OSHA"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: [],
      hitlDefaults: { "outage-communications": "ESCALATE" },
      localOnlyDomains: ["infrastructure-data"],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["utility", "electric", "gas", "water", "power-company", "energy-provider", "municipal-utility", "public-utility", "grid", "ratepayer"],
  },
  {
    id: "energy-renewable",
    name: "Solar / Renewable Energy",
    sector: "energy",
    size: ["small", "medium", "large"],
    description: "Solar, wind, or renewable energy company providing installation and energy services",
    departments: [
      { domain: "General", name: "Engineering", capabilities: ["system-design", "permitting", "interconnection", "energy-modeling"] },
      { domain: "General", name: "Installation", capabilities: ["project-management", "crew-scheduling", "inspections", "commissioning"] },
      { domain: "Marketing", name: "Sales", capabilities: ["lead-generation", "proposals", "consultations", "channel-partnerships"] },
      { domain: "General", name: "Operations", capabilities: ["monitoring", "maintenance", "performance-analysis", "warranty-management"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "project-financing", "incentive-tracking", "budgeting"] },
    ],
    governance: {
      compliance: ["state incentive programs", "OSHA"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["solar", "renewable-energy", "wind", "clean-energy", "solar-installation", "green-energy", "EV-charging", "battery-storage", "sustainability"],
  },
  {
    id: "energy-oilgas",
    name: "Oil & Gas",
    sector: "energy",
    size: ["medium", "large", "enterprise"],
    description: "Oil and gas company involved in exploration, production, or distribution of petroleum products",
    departments: [
      { domain: "General", name: "Operations", capabilities: ["drilling", "production", "pipeline-operations", "processing"] },
      { domain: "General", name: "Engineering", capabilities: ["reservoir-engineering", "facility-design", "project-management", "R&D"] },
      { domain: "General", name: "Safety", capabilities: ["HSE-programs", "incident-investigation", "emergency-response", "training"] },
      { domain: "General", name: "Environmental", capabilities: ["environmental-monitoring", "remediation", "permitting", "impact-assessments"] },
      { domain: "Legal", name: "Regulatory", capabilities: ["EPA-compliance", "state-reporting", "SEC-filings", "land-rights"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "reserves-valuation", "capital-budgeting", "revenue-distribution"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "safety-training", "benefits", "workforce-planning"] },
    ],
    governance: {
      compliance: ["EPA", "OSHA", "SEC"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: [],
      hitlDefaults: { "environmental-incidents": "ESCALATE" },
      localOnlyDomains: ["reserves-data"],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["oil-gas", "petroleum", "drilling", "upstream", "downstream", "midstream", "refinery", "pipeline", "natural-gas", "energy-company"],
  },
];
