module.exports = [
  {
    id: "fin-bank",
    name: "Bank/Credit Union",
    sector: "financial",
    size: ["medium", "large", "enterprise"],
    description: "Bank, credit union, or savings institution with comprehensive financial operations",
    departments: [
      { domain: "RetailBanking", name: "Retail Banking", capabilities: ["deposits", "consumer-lending", "branch-operations", "atm-management", "customer-service"] },
      { domain: "Commercial", name: "Commercial Banking", capabilities: ["commercial-lending", "treasury-management", "business-accounts", "trade-finance"] },
      { domain: "Lending", name: "Lending", capabilities: ["underwriting", "origination", "servicing", "collections", "credit-analysis"] },
      { domain: "Compliance", name: "Compliance", capabilities: ["bsa-aml", "kyc", "regulatory-reporting", "fair-lending", "consumer-protection"] },
      { domain: "Risk", name: "Risk Management", capabilities: ["credit-risk", "market-risk", "operational-risk", "fraud-prevention", "model-validation"] },
      { domain: "Operations", name: "Operations", capabilities: ["payment-processing", "wire-transfers", "ach", "reconciliation", "vault-management"] },
      { domain: "IT", name: "Information Technology", capabilities: ["core-banking", "cybersecurity", "digital-banking", "data-analytics", "infrastructure"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "training", "labor-relations", "licensing"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["brand", "campaigns", "community-outreach", "digital-marketing", "product-marketing"] },
      { domain: "Audit", name: "Internal Audit", capabilities: ["financial-audit", "operational-audit", "compliance-testing", "sox-testing", "reporting"] },
    ],
    governance: {
      compliance: ["SOX", "BSA/AML", "GLBA", "FDIC", "CRA", "TILA", "Reg E", "Reg Z"],
      riskSignals: ["PAYMENT_CARD", "FINANCIAL", "PII"],
      additionalDomains: ["Finance", "Banking"],
      hitlDefaults: { Operations: "ESCALATE", Compliance: "ESCALATE", Lending: "DRAFT" },
      localOnlyDomains: ["Finance"],
      prohibitedTopics: ["insider-trading", "money-laundering-facilitation"],
    },
    discoveryKeywords: ["bank", "credit union", "banking", "savings institution", "financial institution", "commercial bank", "community bank", "thrift", "depository"],
  },
  {
    id: "fin-insurance",
    name: "Insurance Company",
    sector: "financial",
    size: ["medium", "large", "enterprise"],
    description: "Property/casualty, life, or specialty insurance company",
    departments: [
      { domain: "Underwriting", name: "Underwriting", capabilities: ["risk-assessment", "pricing", "policy-issuance", "reinsurance", "appetite-management"] },
      { domain: "Claims", name: "Claims", capabilities: ["investigation", "adjustment", "settlement", "litigation-management", "fraud-detection"] },
      { domain: "Actuarial", name: "Actuarial", capabilities: ["reserving", "pricing-models", "loss-analysis", "capital-modeling", "regulatory-filings"] },
      { domain: "Compliance", name: "Compliance", capabilities: ["state-filings", "market-conduct", "regulatory-reporting", "consumer-protection"] },
      { domain: "Sales", name: "Sales & Distribution", capabilities: ["agent-management", "broker-relations", "product-distribution", "channel-management"] },
      { domain: "IT", name: "Information Technology", capabilities: ["policy-systems", "claims-systems", "cybersecurity", "data-analytics", "infrastructure"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "training", "licensing-management"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "investments", "reserves", "budgeting", "statutory-reporting"] },
    ],
    governance: {
      compliance: ["State Insurance Regulations", "SOX", "NAIC Model Laws", "ORSA"],
      riskSignals: ["PII", "FINANCIAL"],
      additionalDomains: ["Finance", "Insurance"],
      hitlDefaults: { Claims: "DRAFT", Underwriting: "DRAFT", Compliance: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: ["bad-faith-claims-handling"],
    },
    discoveryKeywords: ["insurance", "insurance company", "insurer", "underwriting", "claims", "property casualty", "life insurance", "P&C", "carrier", "insurance carrier"],
  },
  {
    id: "fin-advisory",
    name: "Financial Advisory",
    sector: "financial",
    size: ["solo", "small", "medium"],
    description: "Financial advisory or wealth management firm with fiduciary responsibilities",
    departments: [
      { domain: "Advisory", name: "Advisory Services", capabilities: ["financial-planning", "investment-management", "retirement-planning", "estate-planning", "tax-planning"] },
      { domain: "Compliance", name: "Compliance", capabilities: ["regulatory-filings", "advertising-review", "books-records", "supervision", "aml"] },
      { domain: "Operations", name: "Operations", capabilities: ["account-administration", "trading", "reporting", "custodian-management", "onboarding"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["client-communications", "seminars", "digital-marketing", "referral-programs"] },
    ],
    governance: {
      compliance: ["SEC", "FINRA", "Fiduciary Duty", "Investment Advisers Act", "Reg BI"],
      riskSignals: ["FINANCIAL", "PII"],
      additionalDomains: ["Finance", "InvestmentAdvice"],
      hitlDefaults: { Advisory: "DRAFT", Marketing: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: ["guaranteed-returns", "unsuitable-recommendations"],
    },
    discoveryKeywords: ["financial advisor", "wealth management", "financial planner", "investment advisor", "RIA", "financial consultant", "retirement planning", "estate planning", "CFP", "fiduciary"],
  },
  {
    id: "fin-accounting",
    name: "Accounting/CPA Firm",
    sector: "financial",
    size: ["solo", "small", "medium"],
    description: "Accounting, tax, or CPA firm providing professional financial services",
    departments: [
      { domain: "Tax", name: "Tax Services", capabilities: ["tax-preparation", "tax-planning", "irs-representation", "state-local-tax", "international-tax"] },
      { domain: "Audit", name: "Audit & Assurance", capabilities: ["financial-audits", "reviews", "compilations", "internal-audit", "sox-compliance"] },
      { domain: "Advisory", name: "Advisory Services", capabilities: ["business-valuation", "forensic-accounting", "consulting", "transaction-support"] },
      { domain: "Operations", name: "Operations", capabilities: ["scheduling", "workflow", "quality-control", "file-management", "client-onboarding"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "cpe-tracking", "professional-development"] },
    ],
    governance: {
      compliance: ["AICPA Code of Ethics", "SOX", "PCAOB Standards", "State CPA Board"],
      riskSignals: ["FINANCIAL", "PII"],
      additionalDomains: ["Finance", "ProfessionalServices"],
      hitlDefaults: { Tax: "DRAFT", Audit: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: ["tax-evasion-facilitation"],
    },
    discoveryKeywords: ["accounting", "accountant", "CPA", "bookkeeping", "tax preparation", "audit", "accounting firm", "bookkeeper", "tax services", "enrolled agent", "tax professional"],
  },
  {
    id: "fin-mortgage",
    name: "Mortgage/Lending Company",
    sector: "financial",
    size: ["small", "medium", "large"],
    description: "Mortgage lender, broker, or loan servicing company",
    departments: [
      { domain: "Origination", name: "Origination", capabilities: ["loan-officers", "pre-approval", "applications", "rate-locks", "referral-management"] },
      { domain: "Processing", name: "Processing", capabilities: ["document-collection", "verification", "file-preparation", "conditions-clearing"] },
      { domain: "Underwriting", name: "Underwriting", capabilities: ["credit-analysis", "property-valuation", "risk-assessment", "decision-making", "exceptions"] },
      { domain: "Compliance", name: "Compliance", capabilities: ["tila-respa", "fair-lending", "hmda-reporting", "state-licensing", "quality-control"] },
      { domain: "Servicing", name: "Servicing", capabilities: ["payment-processing", "escrow-management", "loss-mitigation", "foreclosure", "investor-reporting"] },
    ],
    governance: {
      compliance: ["TILA", "RESPA", "HMDA", "Fair Lending", "ECOA", "State Licensing"],
      riskSignals: ["PII", "FINANCIAL"],
      additionalDomains: ["Finance", "Lending"],
      hitlDefaults: { Underwriting: "DRAFT", Compliance: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: ["predatory-lending", "steering"],
    },
    discoveryKeywords: ["mortgage", "mortgage company", "home loan", "lender", "mortgage broker", "loan officer", "refinance", "mortgage servicing", "home lending"],
  },
  {
    id: "fin-fintech",
    name: "Fintech Startup",
    sector: "financial",
    size: ["small", "medium"],
    description: "Financial technology startup or digital payments company",
    departments: [
      { domain: "Engineering", name: "Engineering", capabilities: ["backend", "frontend", "mobile", "payments-integration", "api-development", "devops"] },
      { domain: "Product", name: "Product", capabilities: ["product-management", "ux-research", "design", "analytics", "roadmap"] },
      { domain: "Compliance", name: "Compliance", capabilities: ["money-transmitter-licensing", "pci-compliance", "aml", "regulatory-monitoring"] },
      { domain: "Operations", name: "Operations", capabilities: ["customer-support", "risk-operations", "vendor-management", "fraud-operations"] },
      { domain: "Marketing", name: "Marketing & Growth", capabilities: ["growth", "content", "partnerships", "brand", "community"] },
    ],
    governance: {
      compliance: ["State Money Transmitter Laws", "PCI-DSS", "BSA/AML", "CFPB"],
      riskSignals: ["PAYMENT_CARD", "PII", "FINANCIAL"],
      additionalDomains: ["Finance", "Technology"],
      hitlDefaults: { Compliance: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["fintech", "financial technology", "payments", "digital payments", "neobank", "digital wallet", "payment processing", "money transfer", "blockchain payments", "lending platform"],
  },
];
