module.exports = [
  {
    id: "food-restaurant",
    name: "Restaurant (Full Service)",
    sector: "food",
    size: ["small", "medium"],
    description: "Full-service restaurant with kitchen, dining, and event operations",
    departments: [
      { domain: "Kitchen", name: "Kitchen / Back of House", capabilities: ["menu-development", "food-prep", "inventory", "purchasing", "food-safety", "specials"] },
      { domain: "FrontOfHouse", name: "Front of House", capabilities: ["service", "reservations", "hosting", "bar", "wine-program", "customer-relations"] },
      { domain: "Events", name: "Events & Catering", capabilities: ["private-events", "banquets", "catering", "event-planning", "menus"] },
      { domain: "Finance", name: "Finance", capabilities: ["bookkeeping", "payroll", "food-cost", "cash-management", "vendor-payments", "tax"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "training", "scheduling", "tip-management", "labor-compliance"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["social-media", "reviews-management", "promotions", "website", "loyalty-programs"] },
    ],
    governance: {
      compliance: ["Health Department", "Food Safety / ServSafe", "Liquor License", "OSHA", "Labor Laws"],
      riskSignals: ["FOOD_SAFETY"],
      additionalDomains: ["FoodService"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["restaurant", "dining", "full service restaurant", "fine dining", "casual dining", "eatery", "bistro", "tavern", "grill", "steakhouse", "Italian restaurant", "chef"],
  },
  {
    id: "food-qsr",
    name: "Fast Food/QSR",
    sector: "food",
    size: ["small", "medium", "large"],
    description: "Quick-service or fast-food restaurant, including franchise operations",
    departments: [
      { domain: "Operations", name: "Operations", capabilities: ["food-prep", "drive-through", "counter-service", "food-safety", "speed-of-service", "inventory"] },
      { domain: "Staff", name: "Staff Management", capabilities: ["hiring", "training", "scheduling", "performance", "retention"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["local-marketing", "promotions", "social-media", "menu-boards", "community"] },
      { domain: "Finance", name: "Finance", capabilities: ["bookkeeping", "food-cost", "labor-cost", "payroll", "royalty-reporting"] },
    ],
    governance: {
      compliance: ["Health Department", "Food Safety / ServSafe", "Franchise Agreement", "OSHA", "Labor Laws"],
      riskSignals: ["FOOD_SAFETY"],
      additionalDomains: ["FoodService"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["fast food", "QSR", "quick service", "drive-through", "fast casual", "burger", "pizza", "sandwich shop", "chicken", "taco", "sub shop", "food chain"],
  },
  {
    id: "food-cafe",
    name: "Bakery/Cafe/Donut Shop",
    sector: "food",
    size: ["solo", "small"],
    description: "Small bakery, cafe, coffee shop, or donut shop with simple operations",
    departments: [
      { domain: "Production", name: "Production / Kitchen", capabilities: ["baking", "food-prep", "menu-development", "inventory", "food-safety"] },
      { domain: "Counter", name: "Counter / Service", capabilities: ["customer-service", "order-taking", "barista", "merchandising", "cleaning"] },
      { domain: "Finance", name: "Finance", capabilities: ["bookkeeping", "cash-management", "vendor-payments", "tax"] },
    ],
    governance: {
      compliance: ["Health Department", "Food Safety"],
      riskSignals: ["FOOD_SAFETY"],
      additionalDomains: ["FoodService"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["bakery", "cafe", "coffee shop", "donut shop", "patisserie", "tea house", "juice bar", "smoothie", "bagel shop", "pastry", "confectionery", "dessert shop"],
  },
  {
    id: "food-catering",
    name: "Catering Company",
    sector: "food",
    size: ["small", "medium"],
    description: "Catering company for events, corporate, and private functions",
    departments: [
      { domain: "Kitchen", name: "Kitchen / Production", capabilities: ["menu-development", "food-prep", "food-safety", "allergen-management", "transport"] },
      { domain: "Events", name: "Events", capabilities: ["event-planning", "coordination", "staffing", "setup-teardown", "client-meetings"] },
      { domain: "Sales", name: "Sales", capabilities: ["proposals", "tastings", "client-relations", "corporate-accounts", "wedding-planning"] },
      { domain: "Finance", name: "Finance", capabilities: ["invoicing", "bookkeeping", "food-cost", "payroll", "vendor-payments"] },
    ],
    governance: {
      compliance: ["Health Department", "Food Safety / ServSafe", "Event Permits", "Liquor License"],
      riskSignals: ["FOOD_SAFETY"],
      additionalDomains: ["FoodService", "Events"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["catering", "caterer", "catering company", "event catering", "corporate catering", "wedding catering", "food service", "banquet", "party catering"],
  },
  {
    id: "food-production",
    name: "Food/Beverage Manufacturing",
    sector: "food",
    size: ["medium", "large"],
    description: "Food or beverage manufacturing facility with strict regulatory requirements",
    departments: [
      { domain: "Production", name: "Production", capabilities: ["manufacturing", "processing", "packaging", "line-management", "scheduling"] },
      { domain: "Quality", name: "Quality Assurance", capabilities: ["testing", "haccp", "sanitation", "audits", "recall-management", "allergen-control"] },
      { domain: "RD", name: "Research & Development", capabilities: ["product-development", "formulation", "sensory-testing", "shelf-life", "innovation"] },
      { domain: "Distribution", name: "Distribution & Logistics", capabilities: ["warehousing", "shipping", "cold-chain", "fleet", "order-fulfillment"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "training", "safety-training", "labor-relations"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "budgeting", "cost-analysis", "procurement", "payroll"] },
      { domain: "Regulatory", name: "Regulatory Affairs", capabilities: ["fda-compliance", "labeling", "nutritional-analysis", "certifications", "import-export"] },
    ],
    governance: {
      compliance: ["FDA", "FSMA", "HACCP", "OSHA", "EPA", "cGMP"],
      riskSignals: ["FOOD_SAFETY"],
      additionalDomains: ["FoodService", "Manufacturing"],
      hitlDefaults: { Regulatory: "DRAFT", Quality: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: ["false-labeling", "adulteration"],
    },
    discoveryKeywords: ["food manufacturing", "food production", "beverage manufacturing", "food processing", "food plant", "brewery", "distillery", "winery", "dairy", "meat processing", "cannery", "bottling"],
  },
];
