module.exports = [
  {
    id: "gov-city",
    name: "City/Town Government",
    sector: "government",
    size: ["medium", "large", "enterprise"],
    description: "Full-service municipal government with comprehensive department coverage",
    departments: [
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "labor-relations", "training", "employee-records"] },
      { domain: "Finance", name: "Finance & Budget", capabilities: ["budgeting", "accounts-payable", "accounts-receivable", "payroll", "grants", "audit"] },
      { domain: "Legal", name: "Law Department", capabilities: ["ordinances", "litigation", "contracts", "foia-requests", "ethics"] },
      { domain: "PublicSafety", name: "Public Safety", capabilities: ["police", "fire", "emergency-management", "dispatch", "community-policing"] },
      { domain: "PublicWorks", name: "Public Works", capabilities: ["roads", "water", "sewer", "fleet", "facilities", "snow-removal"] },
      { domain: "Parks", name: "Parks & Recreation", capabilities: ["park-maintenance", "programs", "events", "facilities-rental", "youth-services"] },
      { domain: "IT", name: "Information Technology", capabilities: ["infrastructure", "helpdesk", "cybersecurity", "gis", "website"] },
      { domain: "Communications", name: "Communications & Media", capabilities: ["press-releases", "social-media", "public-notices", "newsletters", "crisis-comms"] },
      { domain: "Building", name: "Building & Housing", capabilities: ["permits", "inspections", "zoning", "code-enforcement", "housing-programs"] },
      { domain: "PublicHealth", name: "Public Health", capabilities: ["health-programs", "inspections", "epidemiology", "community-health", "vital-records"] },
      { domain: "311", name: "311/Constituent Services", capabilities: ["service-requests", "complaint-tracking", "information", "follow-up", "analytics"] },
    ],
    governance: {
      compliance: ["FOIA", "ADA", "Open Meetings Act", "Public Records"],
      riskSignals: ["PII", "CAMPAIGN_FINANCE"],
      additionalDomains: ["Government", "PublicRecords"],
      hitlDefaults: { Communications: "ESCALATE", Legal: "DRAFT", Finance: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: ["campaign-endorsements", "partisan-activity"],
    },
    discoveryKeywords: ["city", "town", "municipal", "municipality", "city hall", "mayor", "council", "alderman", "city government", "local government", "civic", "public service"],
  },
  {
    id: "gov-city-lite",
    name: "Small Town Government",
    sector: "government",
    size: ["small", "medium"],
    description: "Streamlined government template for small towns and villages",
    departments: [
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "employee-records"] },
      { domain: "Finance", name: "Finance", capabilities: ["budgeting", "accounts-payable", "payroll", "tax-collection"] },
      { domain: "PublicSafety", name: "Public Safety", capabilities: ["police", "fire", "emergency-management"] },
      { domain: "Building", name: "Building & Zoning", capabilities: ["permits", "inspections", "zoning", "code-enforcement"] },
    ],
    governance: {
      compliance: ["FOIA", "ADA"],
      riskSignals: ["PII"],
      additionalDomains: ["Government"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: ["campaign-endorsements"],
    },
    discoveryKeywords: ["small town", "village", "township", "borough", "hamlet", "rural government", "small municipality", "town clerk"],
  },
  {
    id: "gov-county",
    name: "County Government",
    sector: "government",
    size: ["medium", "large", "enterprise"],
    description: "County-level government with specialized county departments",
    departments: [
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "labor-relations", "training"] },
      { domain: "Finance", name: "Finance & Budget", capabilities: ["budgeting", "accounts-payable", "payroll", "grants", "audit"] },
      { domain: "Legal", name: "Prosecutor / Law", capabilities: ["prosecution", "litigation", "contracts", "foia-requests"] },
      { domain: "PublicSafety", name: "Sheriff / Public Safety", capabilities: ["sheriff", "corrections", "dispatch", "emergency-management"] },
      { domain: "PublicWorks", name: "Public Works", capabilities: ["roads", "bridges", "water", "sewer", "fleet"] },
      { domain: "Parks", name: "Parks & Conservation", capabilities: ["park-maintenance", "conservation", "trails", "programs"] },
      { domain: "IT", name: "Information Technology", capabilities: ["infrastructure", "helpdesk", "cybersecurity", "gis"] },
      { domain: "Communications", name: "Communications", capabilities: ["press-releases", "social-media", "public-notices"] },
      { domain: "Building", name: "Planning & Development", capabilities: ["permits", "zoning", "land-use", "inspections"] },
      { domain: "PublicHealth", name: "Public Health", capabilities: ["health-programs", "inspections", "epidemiology", "vital-records"] },
      { domain: "Elections", name: "Board of Elections", capabilities: ["voter-registration", "ballot-management", "poll-worker-training", "election-certification"] },
      { domain: "Recorder", name: "County Recorder", capabilities: ["deed-recording", "document-indexing", "vital-records", "notary"] },
      { domain: "Assessor", name: "County Assessor", capabilities: ["property-valuation", "tax-assessment", "appeals", "mapping"] },
      { domain: "Coroner", name: "Coroner / Medical Examiner", capabilities: ["death-investigation", "autopsies", "identification", "records"] },
    ],
    governance: {
      compliance: ["FOIA", "ADA", "Open Meetings Act", "Public Records", "HAVA"],
      riskSignals: ["PII", "CAMPAIGN_FINANCE"],
      additionalDomains: ["Government", "PublicRecords", "Elections"],
      hitlDefaults: { Communications: "ESCALATE", Legal: "DRAFT", Finance: "DRAFT", Elections: "ESCALATE" },
      localOnlyDomains: ["Elections"],
      prohibitedTopics: ["campaign-endorsements", "partisan-activity"],
    },
    discoveryKeywords: ["county", "county government", "commissioner", "county seat", "parish", "county council", "board of supervisors", "county executive"],
  },
  {
    id: "gov-state",
    name: "State Agency",
    sector: "government",
    size: ["large", "enterprise"],
    description: "State-level government agency with regulatory oversight",
    departments: [
      { domain: "Administration", name: "Administration", capabilities: ["policy", "strategic-planning", "operations", "intergovernmental-affairs"] },
      { domain: "Legal", name: "Legal / General Counsel", capabilities: ["rulemaking", "litigation", "contracts", "ethics", "legislative-analysis"] },
      { domain: "IT", name: "Information Technology", capabilities: ["infrastructure", "cybersecurity", "data-governance", "enterprise-systems"] },
      { domain: "Communications", name: "Communications", capabilities: ["press-releases", "social-media", "public-notices", "legislative-testimony"] },
      { domain: "HR", name: "Human Resources", capabilities: ["civil-service", "benefits", "labor-relations", "training"] },
      { domain: "Finance", name: "Finance & Budget", capabilities: ["budgeting", "procurement", "grants", "audit", "fiscal-analysis"] },
      { domain: "Programs", name: "Program Operations", capabilities: ["program-delivery", "case-management", "constituent-services", "regulatory-enforcement"] },
    ],
    governance: {
      compliance: ["FedRAMP", "ADA", "FOIA", "State Administrative Procedures Act"],
      riskSignals: ["PII", "CAMPAIGN_FINANCE"],
      additionalDomains: ["Government", "RegulatoryOversight"],
      hitlDefaults: { Communications: "ESCALATE", Legal: "DRAFT", Finance: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: ["campaign-endorsements", "partisan-activity"],
    },
    discoveryKeywords: ["state agency", "state government", "state department", "governor", "legislature", "state office", "bureau", "division", "commonwealth"],
  },
  {
    id: "gov-federal",
    name: "Federal Agency",
    sector: "government",
    size: ["enterprise"],
    description: "Federal government agency with highest security and compliance requirements",
    departments: [
      { domain: "Administration", name: "Administration", capabilities: ["policy", "strategic-planning", "operations", "interagency-coordination"] },
      { domain: "Legal", name: "Office of General Counsel", capabilities: ["rulemaking", "litigation", "contracts", "foia", "ethics", "legislative-affairs"] },
      { domain: "IT", name: "Information Technology", capabilities: ["infrastructure", "cybersecurity", "cloud-services", "data-governance", "fedramp-management"] },
      { domain: "Communications", name: "Public Affairs", capabilities: ["press-releases", "congressional-relations", "social-media", "public-notices"] },
      { domain: "HR", name: "Human Capital", capabilities: ["federal-hiring", "benefits", "labor-relations", "training", "clearance-management"] },
      { domain: "Finance", name: "Chief Financial Officer", capabilities: ["budgeting", "procurement", "grants", "audit", "appropriations"] },
      { domain: "Programs", name: "Program Operations", capabilities: ["program-delivery", "regulatory-enforcement", "grants-management", "constituent-services"] },
      { domain: "Compliance", name: "Compliance & Inspector General", capabilities: ["internal-audit", "investigations", "whistleblower-protection", "reporting"] },
    ],
    governance: {
      compliance: ["FedRAMP", "FISMA", "Section 508", "FOIA", "Privacy Act", "NIST 800-53"],
      riskSignals: ["PII", "CLASSIFIED"],
      additionalDomains: ["Government", "FederalSecurity", "NationalSecurity"],
      hitlDefaults: { Communications: "ESCALATE", Legal: "DRAFT", Finance: "DRAFT", Compliance: "ESCALATE" },
      localOnlyDomains: ["Administration", "Legal", "IT", "Communications", "HR", "Finance", "Programs", "Compliance"],
      prohibitedTopics: ["campaign-endorsements", "partisan-activity", "classified-material"],
    },
    discoveryKeywords: ["federal", "federal agency", "federal government", "us government", "agency", "department", "bureau", "federal office", "washington dc"],
  },
  {
    id: "gov-tribal",
    name: "Tribal Government",
    sector: "government",
    size: ["small", "medium", "large"],
    description: "Tribal nation government with sovereignty-respecting governance",
    departments: [
      { domain: "Administration", name: "Tribal Administration", capabilities: ["policy", "council-support", "operations", "intergovernmental-affairs"] },
      { domain: "Legal", name: "Tribal Legal", capabilities: ["sovereignty-issues", "treaty-rights", "contracts", "legislative-drafting"] },
      { domain: "Health", name: "Health Services", capabilities: ["clinical-services", "behavioral-health", "community-health", "elder-care"] },
      { domain: "Finance", name: "Finance", capabilities: ["budgeting", "grants", "federal-funding", "audit", "tribal-enterprises"] },
      { domain: "CulturalResources", name: "Cultural Resources", capabilities: ["language-preservation", "cultural-programs", "historic-preservation", "repatriation"] },
    ],
    governance: {
      compliance: ["Tribal Sovereignty", "FOIA", "ADA", "NAGPRA", "IHCIA"],
      riskSignals: ["PII", "CULTURAL_SENSITIVE"],
      additionalDomains: ["Government", "TribalSovereignty", "CulturalPreservation"],
      hitlDefaults: { CulturalResources: "ESCALATE", Legal: "DRAFT" },
      localOnlyDomains: ["CulturalResources"],
      prohibitedTopics: ["sacred-site-locations", "ceremonial-details"],
    },
    discoveryKeywords: ["tribal", "tribe", "tribal government", "tribal nation", "indigenous", "native american", "first nations", "reservation", "sovereign nation", "tribal council"],
  },
];
