module.exports = [
  {
    id: "health-hospital",
    name: "Hospital/Health System",
    sector: "healthcare",
    size: ["large", "enterprise"],
    description: "Hospital or health system with comprehensive clinical and administrative operations",
    departments: [
      { domain: "Clinical", name: "Clinical Services", capabilities: ["patient-care", "surgery", "emergency", "imaging", "specialists", "outpatient"] },
      { domain: "Administration", name: "Administration", capabilities: ["executive-leadership", "strategic-planning", "operations", "credentialing"] },
      { domain: "Billing", name: "Revenue Cycle / Billing", capabilities: ["claims", "coding", "collections", "insurance-verification", "patient-billing"] },
      { domain: "Pharmacy", name: "Pharmacy", capabilities: ["dispensing", "formulary-management", "controlled-substances", "compounding", "clinical-pharmacy"] },
      { domain: "Lab", name: "Laboratory & Pathology", capabilities: ["diagnostics", "blood-bank", "microbiology", "pathology", "point-of-care"] },
      { domain: "Nursing", name: "Nursing", capabilities: ["inpatient-care", "staffing", "education", "quality-metrics", "care-coordination"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "credentialing", "labor-relations", "training"] },
      { domain: "Compliance", name: "Compliance & Risk", capabilities: ["hipaa-compliance", "incident-reporting", "accreditation", "risk-management", "auditing"] },
      { domain: "IT", name: "Information Technology", capabilities: ["ehr", "infrastructure", "cybersecurity", "telehealth", "medical-devices"] },
      { domain: "PatientRelations", name: "Patient Relations", capabilities: ["patient-advocacy", "complaints", "satisfaction-surveys", "interpreter-services"] },
    ],
    governance: {
      compliance: ["HIPAA", "HITECH", "Joint Commission", "CMS Conditions of Participation", "OSHA", "EMTALA"],
      riskSignals: ["PHI"],
      additionalDomains: ["Healthcare", "ClinicalSafety"],
      hitlDefaults: { Clinical: "ESCALATE", Pharmacy: "ESCALATE" },
      localOnlyDomains: ["Healthcare"],
      prohibitedTopics: ["prescribing-without-license", "diagnosis-without-clinician"],
    },
    discoveryKeywords: ["hospital", "health system", "medical center", "clinic", "healthcare", "health care", "patient care", "inpatient", "outpatient", "emergency room", "ER"],
  },
  {
    id: "health-practice",
    name: "Medical/Dental Practice",
    sector: "healthcare",
    size: ["solo", "small", "medium"],
    description: "Private medical or dental practice with streamlined clinical operations",
    departments: [
      { domain: "Clinical", name: "Clinical", capabilities: ["patient-care", "procedures", "referrals", "prescriptions", "preventive-care"] },
      { domain: "FrontOffice", name: "Front Office", capabilities: ["scheduling", "check-in", "insurance-verification", "patient-communications", "records"] },
      { domain: "Billing", name: "Billing", capabilities: ["claims", "coding", "collections", "patient-billing", "insurance-follow-up"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "training", "compliance"] },
    ],
    governance: {
      compliance: ["HIPAA", "OSHA", "State Medical Board"],
      riskSignals: ["PHI", "PII"],
      additionalDomains: ["Healthcare"],
      hitlDefaults: { Clinical: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: ["prescribing-without-license", "diagnosis-without-clinician"],
    },
    discoveryKeywords: ["medical practice", "doctor office", "physician", "dental practice", "dentist", "primary care", "family medicine", "pediatrician", "specialist", "dermatologist", "OB-GYN", "private practice"],
  },
  {
    id: "health-mental",
    name: "Mental/Behavioral Health",
    sector: "healthcare",
    size: ["solo", "small", "medium"],
    description: "Mental health or behavioral health practice with strict confidentiality protections",
    departments: [
      { domain: "Clinical", name: "Clinical Services", capabilities: ["therapy", "assessment", "crisis-intervention", "group-therapy", "medication-management"] },
      { domain: "Administration", name: "Administration", capabilities: ["scheduling", "records", "referrals", "intake", "operations"] },
      { domain: "Billing", name: "Billing", capabilities: ["claims", "insurance-verification", "patient-billing", "authorization"] },
    ],
    governance: {
      compliance: ["HIPAA", "42 CFR Part 2", "State Mental Health Act", "Duty to Warn"],
      riskSignals: ["PHI"],
      additionalDomains: ["Healthcare", "BehavioralHealth"],
      hitlDefaults: { Clinical: "ESCALATE" },
      localOnlyDomains: ["BehavioralHealth"],
      prohibitedTopics: ["substance-abuse-disclosure-without-consent", "diagnosis-without-clinician"],
    },
    discoveryKeywords: ["mental health", "behavioral health", "therapy", "therapist", "psychologist", "psychiatrist", "counseling", "counselor", "substance abuse", "addiction treatment", "rehab", "psychiatric"],
  },
  {
    id: "health-pharmacy",
    name: "Pharmacy",
    sector: "healthcare",
    size: ["small", "medium"],
    description: "Retail, compounding, or specialty pharmacy with controlled substance management",
    departments: [
      { domain: "Dispensing", name: "Dispensing", capabilities: ["prescription-filling", "controlled-substances", "compounding", "otc", "immunizations"] },
      { domain: "Clinical", name: "Clinical Pharmacy", capabilities: ["medication-therapy-management", "drug-interactions", "patient-counseling", "formulary"] },
      { domain: "Operations", name: "Operations", capabilities: ["inventory", "purchasing", "scheduling", "workflow", "delivery"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "insurance-claims", "payer-contracts", "accounting", "payroll"] },
    ],
    governance: {
      compliance: ["HIPAA", "DEA", "State Board of Pharmacy", "FDA"],
      riskSignals: ["PHI", "REGULATED_SUBSTANCE"],
      additionalDomains: ["Healthcare", "PharmaceuticalControl"],
      hitlDefaults: { Dispensing: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: ["controlled-substance-diversion"],
    },
    discoveryKeywords: ["pharmacy", "pharmacist", "drugstore", "prescription", "compounding pharmacy", "specialty pharmacy", "retail pharmacy", "apothecary"],
  },
  {
    id: "health-senior",
    name: "Senior Living/Home Health",
    sector: "healthcare",
    size: ["small", "medium", "large"],
    description: "Senior living community, nursing home, or home health agency",
    departments: [
      { domain: "CareServices", name: "Care Services", capabilities: ["nursing", "personal-care", "rehabilitation", "memory-care", "hospice", "home-health"] },
      { domain: "Administration", name: "Administration", capabilities: ["operations", "admissions", "resident-relations", "activity-programs"] },
      { domain: "Compliance", name: "Compliance & Quality", capabilities: ["survey-readiness", "incident-reporting", "quality-metrics", "cms-compliance"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "training", "certification-tracking", "staffing"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "medicare-medicaid", "accounts-receivable", "budgeting", "payroll"] },
      { domain: "FamilyRelations", name: "Family Relations", capabilities: ["family-communication", "care-conferences", "complaint-resolution", "tours"] },
    ],
    governance: {
      compliance: ["HIPAA", "CMS", "State Licensure", "OSHA", "Elder Abuse Reporting"],
      riskSignals: ["PHI", "PII"],
      additionalDomains: ["Healthcare", "ElderCare"],
      hitlDefaults: { CareServices: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["senior living", "nursing home", "assisted living", "home health", "elder care", "retirement community", "skilled nursing", "memory care", "hospice", "long-term care", "aging"],
  },
  {
    id: "health-vet",
    name: "Veterinary Practice",
    sector: "healthcare",
    size: ["solo", "small", "medium"],
    description: "Veterinary clinic or animal hospital",
    departments: [
      { domain: "Clinical", name: "Clinical", capabilities: ["exams", "surgery", "diagnostics", "dental", "emergency", "preventive-care"] },
      { domain: "FrontOffice", name: "Front Office", capabilities: ["scheduling", "check-in", "client-communications", "records", "reminders"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "inventory", "accounting", "payroll", "vendor-management"] },
    ],
    governance: {
      compliance: ["DEA", "State Veterinary Board", "OSHA"],
      riskSignals: ["REGULATED_SUBSTANCE"],
      additionalDomains: ["Veterinary"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["veterinary", "vet", "veterinarian", "animal hospital", "animal clinic", "pet care", "vet clinic", "animal doctor", "pet hospital"],
  },
  {
    id: "health-insurance",
    name: "Health Insurance/Payer",
    sector: "healthcare",
    size: ["large", "enterprise"],
    description: "Health insurance company, managed care organization, or third-party payer",
    departments: [
      { domain: "Claims", name: "Claims Processing", capabilities: ["adjudication", "appeals", "fraud-detection", "payment-integrity", "coordination-of-benefits"] },
      { domain: "Underwriting", name: "Underwriting", capabilities: ["risk-assessment", "pricing", "plan-design", "actuarial-support"] },
      { domain: "Compliance", name: "Compliance & Regulatory", capabilities: ["state-filings", "market-conduct", "hipaa-compliance", "aca-compliance", "audit"] },
      { domain: "IT", name: "Information Technology", capabilities: ["core-systems", "data-analytics", "cybersecurity", "interoperability", "portal-management"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "training", "labor-relations"] },
      { domain: "Finance", name: "Finance", capabilities: ["reserves", "budgeting", "accounting", "investments", "reporting"] },
      { domain: "CustomerService", name: "Customer Service", capabilities: ["member-support", "provider-support", "grievances", "enrollment", "benefit-inquiries"] },
    ],
    governance: {
      compliance: ["HIPAA", "ACA", "State Insurance Regulations", "ERISA", "NCQA"],
      riskSignals: ["PHI", "PII"],
      additionalDomains: ["Healthcare", "Insurance"],
      hitlDefaults: { Claims: "DRAFT", Compliance: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["health insurance", "health plan", "payer", "managed care", "HMO", "PPO", "insurance company", "claims processing", "health benefits", "third-party administrator", "TPA"],
  },
];
