module.exports = [
  {
    id: "hospitality-hotel",
    name: "Hotel / Resort",
    sector: "hospitality",
    size: ["medium", "large", "enterprise"],
    description: "Hotel or resort property with rooms, food and beverage, and guest services",
    departments: [
      { domain: "General", name: "Front Desk", capabilities: ["check-in-out", "reservations", "guest-services", "concierge"] },
      { domain: "General", name: "Housekeeping", capabilities: ["room-cleaning", "laundry", "inventory", "inspections"] },
      { domain: "General", name: "Food & Beverage", capabilities: ["restaurants", "bars", "room-service", "catering", "menu-planning"] },
      { domain: "General", name: "Events", capabilities: ["event-planning", "conference-services", "banquets", "coordination"] },
      { domain: "Marketing", name: "Sales", capabilities: ["group-sales", "corporate-accounts", "revenue-management", "partnerships"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["branding", "digital-marketing", "loyalty-programs", "reviews-management"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "training", "benefits", "scheduling", "compliance"] },
      { domain: "General", name: "Maintenance", capabilities: ["facilities", "repairs", "preventive-maintenance", "grounds"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "budgeting", "payroll", "reporting", "procurement"] },
    ],
    governance: {
      compliance: ["ADA", "PCI-DSS", "liquor licensing", "health department"],
      riskSignals: ["PAYMENT_CARD", "PII"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["hotel", "resort", "lodging", "hospitality", "accommodation", "guest-services", "inn", "motel", "boutique-hotel", "bed-and-breakfast"],
  },
  {
    id: "hospitality-venue",
    name: "Event Venue / Convention Center",
    sector: "hospitality",
    size: ["small", "medium", "large"],
    description: "Event venue, convention center, or banquet facility hosting gatherings and conferences",
    departments: [
      { domain: "General", name: "Events", capabilities: ["event-coordination", "booking", "client-relations", "setup-teardown"] },
      { domain: "General", name: "Operations", capabilities: ["logistics", "staffing", "vendor-management", "safety"] },
      { domain: "Marketing", name: "Sales", capabilities: ["lead-generation", "proposals", "contracts", "partnerships"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["branding", "advertising", "social-media", "promotions"] },
      { domain: "General", name: "Maintenance", capabilities: ["facilities", "AV-equipment", "repairs", "cleaning"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "invoicing", "budgeting", "procurement"] },
    ],
    governance: {
      compliance: ["ADA", "fire code", "liquor licensing", "event permits"],
      riskSignals: ["PAYMENT_CARD"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["venue", "convention-center", "event-space", "banquet-hall", "conference-center", "meeting-space", "wedding-venue", "reception-hall"],
  },
  {
    id: "hospitality-travel",
    name: "Travel Agency / Tour Operator",
    sector: "hospitality",
    size: ["small", "medium"],
    description: "Travel agency or tour operator providing trip planning and travel services",
    departments: [
      { domain: "General", name: "Travel Planning", capabilities: ["itinerary-design", "booking", "destination-research", "custom-tours"] },
      { domain: "Marketing", name: "Sales", capabilities: ["client-acquisition", "packages", "upselling", "partnerships"] },
      { domain: "General", name: "Customer Service", capabilities: ["support", "changes-cancellations", "emergency-assistance", "feedback"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["branding", "content-creation", "social-media", "promotions"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "invoicing", "commissions", "payment-processing"] },
    ],
    governance: {
      compliance: ["DOT regulations", "IATA accreditation"],
      riskSignals: ["PAYMENT_CARD", "PII"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["travel-agency", "tour-operator", "travel", "tourism", "vacation", "trip-planning", "tours", "travel-agent", "booking"],
  },
  {
    id: "hospitality-campground",
    name: "Campground / RV Park",
    sector: "hospitality",
    size: ["small", "medium"],
    description: "Campground or RV park offering outdoor recreation and site rentals",
    departments: [
      { domain: "General", name: "Operations", capabilities: ["site-management", "reservations", "check-in-out", "grounds-maintenance"] },
      { domain: "General", name: "Guest Services", capabilities: ["customer-support", "activity-coordination", "store-management", "information"] },
      { domain: "General", name: "Maintenance", capabilities: ["facilities", "utilities", "landscaping", "equipment"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "invoicing", "seasonal-budgeting"] },
    ],
    governance: {
      compliance: ["health department", "ADA", "environmental regulations"],
      riskSignals: ["PII"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["campground", "rv-park", "camping", "outdoor-recreation", "glamping", "rv-resort", "camp", "trailer-park"],
  },
];
