module.exports = [
  {
    id: "legal-firm-large",
    name: "Law Firm (Mid/Large)",
    sector: "legal",
    size: ["medium", "large", "enterprise"],
    description: "Mid-size to large law firm with multiple practice groups and strict privilege protections",
    departments: [
      { domain: "PracticeGroups", name: "Practice Groups", capabilities: ["litigation", "corporate", "real-estate", "ip", "employment", "regulatory", "tax"] },
      { domain: "ClientIntake", name: "Client Intake & Conflicts", capabilities: ["new-matters", "conflict-checks", "engagement-letters", "client-screening"] },
      { domain: "Billing", name: "Billing & Finance", capabilities: ["time-tracking", "invoicing", "trust-accounting", "collections", "budgeting"] },
      { domain: "Research", name: "Legal Research", capabilities: ["case-research", "statutory-analysis", "brief-drafting", "document-review", "discovery-support"] },
      { domain: "Compliance", name: "Compliance & Ethics", capabilities: ["bar-compliance", "conflicts-management", "trust-account-audits", "ethics-opinions"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "associate-development", "diversity-programs", "performance"] },
      { domain: "IT", name: "Information Technology", capabilities: ["document-management", "e-discovery", "cybersecurity", "case-management", "infrastructure"] },
    ],
    governance: {
      compliance: ["Attorney-Client Privilege", "Bar Rules of Professional Conduct", "Conflict of Interest Rules", "Trust Account Rules"],
      riskSignals: ["TRADE_SECRET", "PII", "ATTORNEY_CLIENT_PRIVILEGE"],
      additionalDomains: ["Legal", "Litigation"],
      hitlDefaults: { ClientIntake: "ESCALATE", PracticeGroups: "DRAFT", Research: "DRAFT" },
      localOnlyDomains: ["Legal"],
      prohibitedTopics: ["unauthorized-practice-of-law"],
    },
    discoveryKeywords: ["law firm", "attorney", "lawyer", "legal practice", "litigation", "corporate law", "law office", "counsel", "barrister", "solicitor", "legal services"],
  },
  {
    id: "legal-firm-small",
    name: "Law Firm (Solo/Small)",
    sector: "legal",
    size: ["solo", "small"],
    description: "Solo practitioner or small law firm with streamlined operations",
    departments: [
      { domain: "Practice", name: "Practice", capabilities: ["case-management", "litigation", "transactional", "client-meetings", "court-appearances"] },
      { domain: "ClientManagement", name: "Client Management", capabilities: ["intake", "conflict-checks", "client-communications", "scheduling", "file-management"] },
      { domain: "Billing", name: "Billing", capabilities: ["time-tracking", "invoicing", "trust-accounting", "collections"] },
    ],
    governance: {
      compliance: ["Attorney-Client Privilege", "Bar Rules of Professional Conduct", "Conflict of Interest Rules", "Trust Account Rules"],
      riskSignals: ["TRADE_SECRET", "ATTORNEY_CLIENT_PRIVILEGE"],
      additionalDomains: ["Legal"],
      hitlDefaults: { ClientManagement: "ESCALATE", Practice: "DRAFT" },
      localOnlyDomains: ["Legal"],
      prohibitedTopics: ["unauthorized-practice-of-law"],
    },
    discoveryKeywords: ["solo attorney", "small law firm", "solo practitioner", "legal practice", "solo lawyer", "boutique law firm", "small legal office"],
  },
  {
    id: "legal-court",
    name: "Court System",
    sector: "legal",
    size: ["medium", "large"],
    description: "Court system or judicial branch administration",
    departments: [
      { domain: "Clerks", name: "Clerk of Courts", capabilities: ["case-filing", "docketing", "records-management", "jury-management", "document-processing"] },
      { domain: "JudgesChambers", name: "Judges Chambers", capabilities: ["case-research", "opinion-drafting", "scheduling", "case-management"] },
      { domain: "Administration", name: "Court Administration", capabilities: ["budgeting", "operations", "court-reporting", "interpreter-services", "facilities"] },
      { domain: "IT", name: "Information Technology", capabilities: ["case-management-system", "e-filing", "cybersecurity", "courtroom-technology"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "training", "judicial-staff-management"] },
    ],
    governance: {
      compliance: ["Public Records Laws", "Sealed Proceedings Rules", "Judicial Ethics", "ADA", "Court Rules"],
      riskSignals: ["PII", "SEALED_RECORDS"],
      additionalDomains: ["Legal", "Judicial"],
      hitlDefaults: { JudgesChambers: "ESCALATE", Clerks: "ESCALATE" },
      localOnlyDomains: ["Judicial"],
      prohibitedTopics: ["ex-parte-communications", "sealed-case-disclosure"],
    },
    discoveryKeywords: ["court", "courthouse", "judicial", "judge", "clerk of courts", "court system", "judiciary", "magistrate", "court administration", "municipal court", "common pleas"],
  },
];
