module.exports = [
  {
    id: "mfg-general",
    name: "General Manufacturing",
    sector: "manufacturing",
    size: ["medium", "large", "enterprise"],
    description: "General manufacturing facility producing discrete or process goods",
    departments: [
      { domain: "Production", name: "Production", capabilities: ["manufacturing", "assembly", "machining", "scheduling", "lean-operations", "maintenance"] },
      { domain: "Quality", name: "Quality Assurance", capabilities: ["inspection", "testing", "iso-compliance", "corrective-actions", "supplier-quality", "calibration"] },
      { domain: "Engineering", name: "Engineering", capabilities: ["process-engineering", "tooling", "automation", "continuous-improvement", "cad-design"] },
      { domain: "SupplyChain", name: "Supply Chain", capabilities: ["procurement", "inventory", "logistics", "warehousing", "vendor-management", "demand-planning"] },
      { domain: "Safety", name: "Safety & Environmental", capabilities: ["osha-compliance", "incident-investigation", "epa-compliance", "waste-management", "training"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "labor-relations", "training", "apprenticeships"] },
      { domain: "Finance", name: "Finance", capabilities: ["cost-accounting", "budgeting", "payroll", "capital-expenditures", "tax"] },
      { domain: "RD", name: "Research & Development", capabilities: ["product-design", "prototyping", "materials-science", "testing", "innovation"] },
    ],
    governance: {
      compliance: ["OSHA", "EPA", "ISO 9001", "ISO 14001"],
      riskSignals: ["SAFETY_INCIDENT", "TRADE_SECRET"],
      additionalDomains: ["Manufacturing", "WorkplaceSafety"],
      hitlDefaults: { Quality: "ESCALATE", Safety: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["manufacturing", "factory", "plant", "production", "assembly", "fabrication", "machining", "industrial", "manufacturer", "OEM", "contract manufacturing"],
  },
  {
    id: "mfg-food",
    name: "Food/Beverage Manufacturing",
    sector: "manufacturing",
    size: ["medium", "large"],
    description: "Food or beverage manufacturing with FDA and food safety compliance",
    departments: [
      { domain: "Production", name: "Production", capabilities: ["manufacturing", "processing", "packaging", "line-management", "batch-control"] },
      { domain: "Quality", name: "Quality Assurance", capabilities: ["haccp", "testing", "sanitation", "audits", "recall-management", "allergen-control"] },
      { domain: "RD", name: "Research & Development", capabilities: ["product-development", "formulation", "sensory-testing", "shelf-life", "nutrition-analysis"] },
      { domain: "Distribution", name: "Distribution", capabilities: ["warehousing", "cold-chain", "shipping", "fleet", "order-fulfillment"] },
      { domain: "Regulatory", name: "Regulatory Affairs", capabilities: ["fda-compliance", "labeling", "certifications", "import-export", "claims-review"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "safety-training", "labor-relations"] },
      { domain: "Finance", name: "Finance", capabilities: ["cost-accounting", "budgeting", "procurement", "payroll"] },
    ],
    governance: {
      compliance: ["FDA", "FSMA", "HACCP", "OSHA", "EPA", "cGMP"],
      riskSignals: ["FOOD_SAFETY", "SAFETY_INCIDENT"],
      additionalDomains: ["Manufacturing", "FoodSafety"],
      hitlDefaults: { Quality: "ESCALATE", Regulatory: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: ["false-labeling", "adulteration"],
    },
    discoveryKeywords: ["food manufacturing", "food production", "beverage manufacturing", "food plant", "food processing", "brewery", "distillery", "dairy plant", "meat plant", "bakery production", "bottling plant"],
  },
  {
    id: "mfg-pharma",
    name: "Pharmaceutical Manufacturing",
    sector: "manufacturing",
    size: ["large", "enterprise"],
    description: "Pharmaceutical or biopharmaceutical manufacturing with strict GMP compliance",
    departments: [
      { domain: "Production", name: "Production", capabilities: ["batch-manufacturing", "sterile-processing", "packaging", "equipment-qualification", "cleaning-validation"] },
      { domain: "Quality", name: "Quality Assurance / QC", capabilities: ["batch-review", "stability-testing", "deviation-management", "capa", "lab-testing", "auditing"] },
      { domain: "RD", name: "Research & Development", capabilities: ["drug-development", "formulation", "clinical-trials", "analytical-methods", "scale-up"] },
      { domain: "Regulatory", name: "Regulatory Affairs", capabilities: ["fda-submissions", "anda-nda", "post-market", "labeling", "international-registrations"] },
      { domain: "Compliance", name: "Compliance", capabilities: ["cgmp-compliance", "dea-reporting", "data-integrity", "investigations", "training"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "gmp-training", "labor-relations"] },
      { domain: "Finance", name: "Finance", capabilities: ["cost-accounting", "budgeting", "capital-planning", "procurement", "tax"] },
    ],
    governance: {
      compliance: ["FDA", "cGMP", "DEA", "HIPAA", "ICH Guidelines", "EPA"],
      riskSignals: ["REGULATED_SUBSTANCE", "PHI", "TRADE_SECRET"],
      additionalDomains: ["Manufacturing", "Pharmaceutical", "Healthcare"],
      hitlDefaults: { Quality: "ESCALATE", Regulatory: "DRAFT", Compliance: "ESCALATE" },
      localOnlyDomains: ["Pharmaceutical"],
      prohibitedTopics: ["formulation-disclosure", "controlled-substance-diversion"],
    },
    discoveryKeywords: ["pharmaceutical", "pharma", "drug manufacturing", "biotech", "biopharmaceutical", "GMP", "cGMP", "pharmaceutical plant", "drug production", "generic drugs", "biologics"],
  },
  {
    id: "mfg-defense",
    name: "Defense/Aerospace Manufacturing",
    sector: "manufacturing",
    size: ["large", "enterprise"],
    description: "Defense or aerospace manufacturing with export control and security requirements",
    departments: [
      { domain: "Production", name: "Production", capabilities: ["manufacturing", "assembly", "integration", "testing", "maintenance-repair-overhaul"] },
      { domain: "Engineering", name: "Engineering", capabilities: ["design", "systems-engineering", "testing", "simulation", "reliability", "configuration-management"] },
      { domain: "Quality", name: "Quality Assurance", capabilities: ["inspection", "testing", "as9100", "first-article", "nonconformance", "supplier-quality"] },
      { domain: "Security", name: "Security", capabilities: ["facility-security", "clearance-management", "itar-compliance", "classified-handling", "visitor-control"] },
      { domain: "Compliance", name: "Compliance & Contracts", capabilities: ["dfars-compliance", "far-compliance", "export-control", "contract-administration", "auditing"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "clearance-processing", "benefits", "training", "labor-relations"] },
      { domain: "Finance", name: "Finance", capabilities: ["government-accounting", "cas-compliance", "budgeting", "procurement", "cost-proposals"] },
    ],
    governance: {
      compliance: ["ITAR", "DFARS", "NIST 800-171", "CMMC", "FAR", "AS9100", "OSHA"],
      riskSignals: ["TRADE_SECRET", "CLASSIFIED"],
      additionalDomains: ["Manufacturing", "Defense", "NationalSecurity"],
      hitlDefaults: { Security: "ESCALATE", Compliance: "ESCALATE", Engineering: "ESCALATE" },
      localOnlyDomains: ["Production", "Engineering", "Quality", "Security", "Compliance", "HR", "Finance"],
      prohibitedTopics: ["classified-disclosure", "export-control-violation"],
    },
    discoveryKeywords: ["defense", "aerospace", "defense contractor", "military", "DoD", "defense manufacturing", "aerospace manufacturing", "munitions", "weapons systems", "avionics", "ITAR"],
  },
];
