module.exports = [
  {
    id: "media-publisher",
    name: "Media / Publishing Company",
    sector: "media",
    size: ["small", "medium", "large"],
    description: "Media company or publisher producing editorial content across print and digital channels",
    departments: [
      { domain: "General", name: "Editorial", capabilities: ["content-creation", "editing", "fact-checking", "editorial-calendar"] },
      { domain: "General", name: "Production", capabilities: ["layout-design", "print-production", "digital-publishing", "quality-control"] },
      { domain: "Marketing", name: "Sales & Advertising", capabilities: ["ad-sales", "sponsorships", "client-relations", "rate-cards"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["audience-growth", "subscriptions", "branding", "social-media"] },
      { domain: "Legal", name: "Legal", capabilities: ["copyright", "defamation-review", "contracts", "licensing", "IP-protection"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "freelancer-management", "benefits", "training"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "ad-revenue", "subscriptions-billing", "budgeting"] },
      { domain: "IT", name: "Digital", capabilities: ["CMS-management", "website-operations", "analytics", "SEO"] },
    ],
    governance: {
      compliance: ["First Amendment", "defamation law", "copyright law"],
      riskSignals: ["TRADE_SECRET"],
      additionalDomains: ["Marketing"],
      hitlDefaults: { "published-content": "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["publishing", "media", "editorial", "magazine", "newspaper", "digital-media", "content-publishing", "press", "journalism", "online-media"],
  },
  {
    id: "media-broadcast",
    name: "Broadcasting (TV / Radio)",
    sector: "media",
    size: ["medium", "large"],
    description: "Television or radio broadcasting operation producing and airing content",
    departments: [
      { domain: "General", name: "Production", capabilities: ["content-production", "scheduling", "studio-operations", "post-production"] },
      { domain: "General", name: "News", capabilities: ["reporting", "anchoring", "investigation", "breaking-news", "fact-checking"] },
      { domain: "Marketing", name: "Sales", capabilities: ["airtime-sales", "sponsorships", "client-relations", "ratings-analysis"] },
      { domain: "General", name: "Engineering", capabilities: ["broadcast-equipment", "transmission", "IT-infrastructure", "FCC-compliance"] },
      { domain: "Legal", name: "Legal", capabilities: ["FCC-regulations", "licensing", "contracts", "content-review"] },
      { domain: "HR", name: "Human Resources", capabilities: ["talent-management", "hiring", "benefits", "union-relations"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "ad-revenue", "budgeting", "payroll"] },
    ],
    governance: {
      compliance: ["FCC regulations", "First Amendment"],
      riskSignals: ["PUBLIC_STATEMENT"],
      additionalDomains: [],
      hitlDefaults: { "broadcast-content": "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["broadcasting", "television", "radio", "TV-station", "radio-station", "broadcast", "news-station", "media-company", "cable", "streaming"],
  },
  {
    id: "media-sports",
    name: "Sports Organization",
    sector: "media",
    size: ["medium", "large", "enterprise"],
    description: "Sports team, league, or organization managing athletic operations and entertainment",
    departments: [
      { domain: "General", name: "Operations", capabilities: ["game-day-ops", "facility-management", "scheduling", "logistics"] },
      { domain: "General", name: "Coaching & Talent", capabilities: ["player-development", "scouting", "analytics", "training"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["branding", "sponsorships", "fan-engagement", "social-media", "merchandise"] },
      { domain: "Legal", name: "Legal", capabilities: ["contracts", "IP-licensing", "league-compliance", "CBA-negotiations"] },
      { domain: "General", name: "Ticketing", capabilities: ["ticket-sales", "season-tickets", "group-sales", "pricing"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "revenue-sharing", "salary-cap", "budgeting"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "benefits", "staff-management", "credentialing"] },
    ],
    governance: {
      compliance: ["league rules", "collective bargaining agreement", "IP licensing"],
      riskSignals: ["TRADE_SECRET"],
      additionalDomains: [],
      hitlDefaults: { "player-trade-info": "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["sports", "team", "league", "athletic", "franchise", "stadium", "arena", "esports", "sports-organization", "club"],
  },
  {
    id: "media-entertainment",
    name: "Entertainment Venue / Promoter",
    sector: "media",
    size: ["small", "medium", "large"],
    description: "Entertainment venue or event promoter producing concerts, shows, and live experiences",
    departments: [
      { domain: "General", name: "Events", capabilities: ["event-booking", "artist-relations", "scheduling", "coordination"] },
      { domain: "General", name: "Production", capabilities: ["stage-management", "sound-lighting", "technical-setup", "crew-management"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["promotion", "advertising", "social-media", "partnerships"] },
      { domain: "General", name: "Ticketing", capabilities: ["ticket-sales", "box-office", "pricing", "distribution"] },
      { domain: "General", name: "Operations", capabilities: ["venue-management", "security", "concessions", "parking"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "settlements", "budgeting", "vendor-payments"] },
    ],
    governance: {
      compliance: ["ASCAP/BMI licensing", "ADA", "fire code", "event permits"],
      riskSignals: ["PAYMENT_CARD"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["entertainment", "concert-venue", "promoter", "live-events", "theater", "performing-arts", "nightclub", "music-venue", "comedy-club", "amphitheater"],
  },
];
