module.exports = [
  {
    id: "nonprofit-general",
    name: "General Nonprofit",
    sector: "nonprofit",
    size: ["small", "medium"],
    description: "General nonprofit organization with donor management and program delivery",
    departments: [
      { domain: "Programs", name: "Programs", capabilities: ["program-design", "impact-measurement", "beneficiary-services", "reporting"] },
      { domain: "Marketing", name: "Development & Fundraising", capabilities: ["donor-relations", "grant-writing", "campaigns", "events", "major-gifts"] },
      { domain: "Comms", name: "Communications", capabilities: ["public-relations", "newsletters", "social-media", "annual-reports"] },
      { domain: "Finance", name: "Finance", capabilities: ["budgeting", "accounting", "audit", "tax-reporting", "restricted-funds"] },
      { domain: "General", name: "Volunteers", capabilities: ["recruitment", "scheduling", "training", "recognition"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "benefits", "policies", "staff-development"] },
    ],
    governance: {
      compliance: ["IRS 501(c)(3)", "state charity registration"],
      riskSignals: ["PII"],
      additionalDomains: [],
      hitlDefaults: { "donor-communications": "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["nonprofit", "charity", "501c3", "donation", "fundraising", "philanthropy", "ngo", "mission-driven", "tax-exempt", "beneficiary"],
  },
  {
    id: "nonprofit-foundation",
    name: "Foundation / Philanthropy",
    sector: "nonprofit",
    size: ["small", "medium", "large"],
    description: "Private or community foundation managing grantmaking and philanthropic programs",
    departments: [
      { domain: "Programs", name: "Grantmaking", capabilities: ["grant-review", "due-diligence", "award-management", "impact-assessment"] },
      { domain: "Programs", name: "Programs", capabilities: ["program-design", "partnerships", "initiative-management"] },
      { domain: "Finance", name: "Finance", capabilities: ["endowment-management", "budgeting", "audit", "tax-reporting", "investment-oversight"] },
      { domain: "Legal", name: "Legal", capabilities: ["compliance", "contracts", "fiduciary-oversight", "governance"] },
      { domain: "Comms", name: "Communications", capabilities: ["annual-reports", "public-relations", "stakeholder-engagement"] },
    ],
    governance: {
      compliance: ["IRS 501(c)(3)", "grant compliance", "fiduciary duty"],
      riskSignals: ["FINANCIAL"],
      additionalDomains: [],
      hitlDefaults: { "grant-reporting": "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["foundation", "philanthropy", "grantmaking", "endowment", "grant", "charitable-giving", "community-foundation", "private-foundation", "donor-advised"],
  },
  {
    id: "nonprofit-religious",
    name: "Religious Organization",
    sector: "nonprofit",
    size: ["small", "medium", "large"],
    description: "Church, mosque, synagogue, or other religious institution with ministry and congregation services",
    departments: [
      { domain: "General", name: "Ministry", capabilities: ["worship", "pastoral-care", "education", "outreach", "youth-programs"] },
      { domain: "General", name: "Administration", capabilities: ["scheduling", "membership", "records", "office-management"] },
      { domain: "Finance", name: "Finance", capabilities: ["tithes-offerings", "budgeting", "accounting", "tax-reporting"] },
      { domain: "Comms", name: "Communications", capabilities: ["bulletins", "newsletters", "website", "social-media", "announcements"] },
      { domain: "General", name: "Facilities", capabilities: ["maintenance", "space-scheduling", "events", "safety"] },
      { domain: "General", name: "Volunteers", capabilities: ["recruitment", "scheduling", "ministry-teams", "training"] },
    ],
    governance: {
      compliance: ["IRS tax exemption", "clergy privilege"],
      riskSignals: ["PII"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["church", "religious", "faith", "ministry", "worship", "congregation", "synagogue", "mosque", "temple", "parish"],
  },
  {
    id: "nonprofit-community",
    name: "Community Organization",
    sector: "nonprofit",
    size: ["small", "medium"],
    description: "Grassroots or community-based organization delivering local programs and services",
    departments: [
      { domain: "Programs", name: "Programs", capabilities: ["community-programs", "service-delivery", "impact-tracking"] },
      { domain: "Comms", name: "Outreach", capabilities: ["community-engagement", "partnerships", "events", "social-media"] },
      { domain: "Finance", name: "Finance", capabilities: ["budgeting", "accounting", "grant-management"] },
      { domain: "General", name: "Volunteers", capabilities: ["recruitment", "scheduling", "coordination"] },
    ],
    governance: {
      compliance: ["state incorporation", "grant requirements"],
      riskSignals: ["PII"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["community", "grassroots", "neighborhood", "civic", "local-organization", "community-service", "mutual-aid", "outreach"],
  },
  {
    id: "nonprofit-advocacy",
    name: "Advocacy / Political Organization",
    sector: "nonprofit",
    size: ["small", "medium"],
    description: "Advocacy group, PAC, or 501(c)(4) organization focused on policy and political engagement",
    departments: [
      { domain: "General", name: "Policy", capabilities: ["research", "analysis", "position-papers", "legislative-tracking"] },
      { domain: "Comms", name: "Communications", capabilities: ["media-relations", "public-statements", "social-media", "campaigns"] },
      { domain: "Marketing", name: "Fundraising", capabilities: ["donor-relations", "campaigns", "events", "compliance-reporting"] },
      { domain: "Legal", name: "Legal", capabilities: ["lobbying-compliance", "FEC-reporting", "election-law", "governance"] },
      { domain: "Finance", name: "Finance", capabilities: ["budgeting", "accounting", "campaign-finance-tracking", "disclosure"] },
    ],
    governance: {
      compliance: ["FEC regulations", "lobbying disclosure", "IRS 501(c)(4)"],
      riskSignals: ["CAMPAIGN_FINANCE"],
      additionalDomains: [],
      hitlDefaults: { "political-statements": "ESCALATE", "external-communications": "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["advocacy", "political", "PAC", "lobbying", "501c4", "policy", "campaign", "civic-engagement", "grassroots-advocacy", "issue-advocacy"],
  },
];
