module.exports = [
  {
    id: "personal-salon",
    name: "Salon / Barbershop / Spa",
    sector: "personal-care",
    size: ["solo", "small", "medium"],
    description: "Hair salon, barbershop, or spa providing personal grooming and wellness services",
    departments: [
      { domain: "General", name: "Services", capabilities: ["hair-services", "skin-care", "nail-services", "massage", "scheduling"] },
      { domain: "General", name: "Client Relations", capabilities: ["booking", "customer-communication", "loyalty-programs", "feedback"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["social-media", "promotions", "branding", "referrals", "portfolio"] },
      { domain: "Finance", name: "Finance", capabilities: ["invoicing", "payroll", "product-sales", "budgeting"] },
      { domain: "HR", name: "Staff", capabilities: ["hiring", "scheduling", "training", "booth-rental-management"] },
    ],
    governance: {
      compliance: ["state cosmetology board", "OSHA", "ADA"],
      riskSignals: ["PII"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["salon", "barbershop", "spa", "hair-stylist", "beauty", "grooming", "nail-salon", "day-spa", "barber", "esthetician"],
  },
  {
    id: "personal-fitness",
    name: "Gym / Fitness Center",
    sector: "personal-care",
    size: ["small", "medium", "large"],
    description: "Gym, fitness center, or studio offering exercise programs and memberships",
    departments: [
      { domain: "General", name: "Programs", capabilities: ["group-fitness", "personal-training", "class-scheduling", "program-design"] },
      { domain: "General", name: "Membership", capabilities: ["enrollment", "retention", "billing", "member-services"] },
      { domain: "General", name: "Operations", capabilities: ["facility-management", "equipment-maintenance", "cleaning", "safety"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["promotions", "social-media", "community-events", "branding"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "membership-billing", "payroll", "budgeting"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "trainer-certification", "scheduling", "benefits"] },
    ],
    governance: {
      compliance: ["ADA", "liability waivers", "OSHA"],
      riskSignals: ["PII"],
      additionalDomains: [],
      hitlDefaults: { "health-wellness-claims": "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["gym", "fitness", "health-club", "workout", "personal-training", "crossfit", "yoga-studio", "pilates", "fitness-center", "exercise"],
  },
  {
    id: "personal-wellness",
    name: "Wellness / Alternative Health",
    sector: "personal-care",
    size: ["solo", "small"],
    description: "Wellness practitioner or alternative health practice offering holistic services",
    departments: [
      { domain: "General", name: "Practice", capabilities: ["client-sessions", "assessments", "treatment-planning", "scheduling"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["content-creation", "social-media", "website", "referrals"] },
      { domain: "Finance", name: "Finance", capabilities: ["invoicing", "insurance-billing", "tax-preparation", "budgeting"] },
    ],
    governance: {
      compliance: ["state licensing", "FTC advertising guidelines"],
      riskSignals: ["PII"],
      additionalDomains: [],
      hitlDefaults: { "health-claims": "DRAFT", "medical-advice": "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["wellness", "alternative-health", "holistic", "acupuncture", "naturopath", "chiropractor", "massage-therapy", "integrative-health", "reiki", "herbalist"],
  },
];
