module.exports = [
  {
    id: "realestate-agency",
    name: "Real Estate Agency",
    sector: "realestate",
    size: ["small", "medium"],
    description: "Real estate brokerage or agency handling sales and leasing",
    departments: [
      { domain: "Sales", name: "Sales", capabilities: ["listings", "buyer-representation", "negotiations", "closings", "market-analysis", "open-houses"] },
      { domain: "Leasing", name: "Leasing", capabilities: ["tenant-screening", "lease-negotiation", "lease-administration", "renewals"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["listing-photography", "mls", "digital-marketing", "staging", "social-media", "brand"] },
      { domain: "Finance", name: "Finance", capabilities: ["commissions", "bookkeeping", "trust-accounts", "tax", "budgeting"] },
    ],
    governance: {
      compliance: ["Fair Housing Act", "State Real Estate Licensing", "RESPA", "Truth in Advertising"],
      riskSignals: ["TENANT_DATA", "PII"],
      additionalDomains: ["RealEstate"],
      hitlDefaults: { Marketing: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: ["discriminatory-steering", "blockbusting"],
    },
    discoveryKeywords: ["real estate", "realtor", "real estate agent", "brokerage", "real estate office", "realty", "property sales", "real estate broker", "listing agent", "buyer agent"],
  },
  {
    id: "realestate-property",
    name: "Property Management",
    sector: "realestate",
    size: ["small", "medium", "large"],
    description: "Property management company for residential or commercial properties",
    departments: [
      { domain: "PropertyMgmt", name: "Property Management", capabilities: ["tenant-relations", "lease-enforcement", "inspections", "compliance", "reporting"] },
      { domain: "Maintenance", name: "Maintenance", capabilities: ["work-orders", "preventive-maintenance", "contractors", "emergency-repairs", "capital-projects"] },
      { domain: "Leasing", name: "Leasing", capabilities: ["marketing-vacancies", "tenant-screening", "lease-execution", "renewals", "move-in-move-out"] },
      { domain: "Finance", name: "Finance", capabilities: ["rent-collection", "accounts-payable", "owner-distributions", "budgeting", "tax-reporting"] },
      { domain: "CustomerService", name: "Customer Service", capabilities: ["tenant-support", "owner-communications", "complaint-resolution", "after-hours"] },
    ],
    governance: {
      compliance: ["Fair Housing Act", "State Landlord-Tenant Law", "Building Codes", "ADA", "Lead Paint Disclosure"],
      riskSignals: ["TENANT_DATA", "PII"],
      additionalDomains: ["RealEstate", "PropertyManagement"],
      hitlDefaults: { PropertyMgmt: "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: ["discriminatory-practices", "retaliatory-eviction"],
    },
    discoveryKeywords: ["property management", "property manager", "landlord", "apartment management", "rental management", "HOA management", "commercial property management", "residential management", "building management"],
  },
  {
    id: "realestate-development",
    name: "Real Estate Development",
    sector: "realestate",
    size: ["medium", "large"],
    description: "Real estate development company handling new construction and redevelopment projects",
    departments: [
      { domain: "Development", name: "Development", capabilities: ["site-selection", "entitlements", "planning", "community-relations", "government-approvals"] },
      { domain: "Construction", name: "Construction Management", capabilities: ["project-management", "contractor-oversight", "scheduling", "quality-control", "safety"] },
      { domain: "Finance", name: "Finance", capabilities: ["project-finance", "investor-relations", "pro-formas", "accounting", "tax-credits"] },
      { domain: "Legal", name: "Legal", capabilities: ["land-use", "contracts", "environmental", "title", "dispute-resolution"] },
      { domain: "Marketing", name: "Marketing & Sales", capabilities: ["pre-sales", "branding", "model-units", "broker-relations", "digital-marketing"] },
    ],
    governance: {
      compliance: ["Zoning Laws", "Environmental Regulations", "OSHA", "Building Codes", "Fair Housing"],
      riskSignals: ["FINANCIAL", "PII"],
      additionalDomains: ["RealEstate", "Construction"],
      hitlDefaults: { Legal: "DRAFT", Finance: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["real estate developer", "real estate development", "property development", "construction development", "land developer", "redevelopment", "mixed-use", "residential development", "commercial development"],
  },
];
