module.exports = [
  {
    id: "retail-chain",
    name: "Retail Chain",
    sector: "retail",
    size: ["medium", "large", "enterprise"],
    description: "Multi-location retail chain with centralized and store-level operations",
    departments: [
      { domain: "StoreOperations", name: "Store Operations", capabilities: ["store-management", "visual-merchandising", "loss-prevention", "customer-experience", "staffing"] },
      { domain: "Inventory", name: "Inventory & Supply Chain", capabilities: ["purchasing", "warehouse", "distribution", "demand-planning", "vendor-management"] },
      { domain: "CustomerService", name: "Customer Service", capabilities: ["returns", "complaints", "loyalty-programs", "feedback", "escalations"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["brand", "promotions", "advertising", "digital-marketing", "social-media", "events"] },
      { domain: "ECommerce", name: "E-Commerce", capabilities: ["online-store", "fulfillment", "marketplace-management", "seo", "conversion-optimization"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "training", "labor-scheduling", "compliance"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "budgeting", "real-estate", "payroll", "tax", "lease-management"] },
    ],
    governance: {
      compliance: ["PCI-DSS", "ADA", "FTC", "State Consumer Protection"],
      riskSignals: ["PAYMENT_CARD", "PII"],
      additionalDomains: ["Retail", "ConsumerData"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["retail chain", "retail store", "department store", "big box", "retail company", "stores", "merchandise", "retail operations", "brick and mortar", "shopping"],
  },
  {
    id: "retail-small",
    name: "Small Retail Shop",
    sector: "retail",
    size: ["solo", "small"],
    description: "Independent retail shop or boutique with lightweight operations",
    departments: [
      { domain: "Sales", name: "Sales", capabilities: ["customer-service", "merchandising", "point-of-sale", "upselling", "product-knowledge"] },
      { domain: "Inventory", name: "Inventory", capabilities: ["ordering", "receiving", "stock-management", "vendor-relations"] },
      { domain: "Finance", name: "Finance", capabilities: ["bookkeeping", "cash-management", "tax", "budgeting"] },
    ],
    governance: {
      compliance: ["PCI-DSS", "ADA"],
      riskSignals: ["PAYMENT_CARD"],
      additionalDomains: ["Retail"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["small shop", "boutique", "retail shop", "store", "small retail", "independent retailer", "specialty shop", "gift shop", "mom and pop"],
  },
  {
    id: "retail-ecommerce",
    name: "E-Commerce Business",
    sector: "retail",
    size: ["small", "medium", "large"],
    description: "Online-first or pure e-commerce business with digital operations",
    departments: [
      { domain: "Operations", name: "Operations & Fulfillment", capabilities: ["order-management", "shipping", "warehouse", "returns", "inventory"] },
      { domain: "CustomerService", name: "Customer Service", capabilities: ["support-tickets", "live-chat", "returns-processing", "reviews", "escalations"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["seo", "sem", "email-marketing", "social-media", "influencer", "content", "affiliate"] },
      { domain: "IT", name: "Information Technology", capabilities: ["platform-management", "cybersecurity", "analytics", "integrations", "payment-processing"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "tax-compliance", "budgeting", "payment-reconciliation", "forecasting"] },
    ],
    governance: {
      compliance: ["PCI-DSS", "CCPA/GDPR", "FTC", "CAN-SPAM", "State Sales Tax"],
      riskSignals: ["PAYMENT_CARD", "PII"],
      additionalDomains: ["Retail", "DigitalCommerce", "ConsumerPrivacy"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: ["deceptive-advertising"],
    },
    discoveryKeywords: ["e-commerce", "ecommerce", "online store", "online retail", "web store", "shopify", "amazon seller", "online business", "DTC", "direct to consumer", "dropshipping"],
  },
  {
    id: "retail-franchise",
    name: "Franchise",
    sector: "retail",
    size: ["small", "medium"],
    description: "Franchise location or multi-unit franchise operator",
    departments: [
      { domain: "Operations", name: "Operations", capabilities: ["store-management", "brand-standards", "quality-control", "opening-closing", "compliance"] },
      { domain: "Staff", name: "Staff Management", capabilities: ["hiring", "training", "scheduling", "performance", "retention"] },
      { domain: "Marketing", name: "Local Marketing", capabilities: ["local-advertising", "community-events", "social-media", "promotions"] },
      { domain: "Finance", name: "Finance", capabilities: ["bookkeeping", "royalty-reporting", "payroll", "budgeting", "tax"] },
    ],
    governance: {
      compliance: ["Franchise Agreement", "PCI-DSS", "Franchisor Operations Manual", "ADA"],
      riskSignals: ["PAYMENT_CARD", "PII"],
      additionalDomains: ["Retail", "Franchise"],
      hitlDefaults: { Marketing: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: ["franchisor-disparagement"],
    },
    discoveryKeywords: ["franchise", "franchisee", "franchise owner", "franchise operator", "multi-unit", "franchise location", "chain restaurant franchise", "franchise business"],
  },
];
