module.exports = [
  {
    id: "solo-freelancer",
    name: "Freelancer",
    sector: "solopreneur",
    size: ["solo"],
    description: "Independent freelancer managing projects, clients, and self-employment obligations",
    departments: [
      { domain: "General", name: "Work Management", capabilities: ["project-tracking", "client-communication", "deliverables", "time-tracking"] },
      { domain: "Finance", name: "Finance", capabilities: ["invoicing", "tax-preparation", "1099-tracking", "expense-management", "budgeting"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["portfolio", "social-media", "networking", "personal-branding", "lead-generation"] },
    ],
    governance: {
      compliance: ["self-employment tax", "1099 reporting"],
      riskSignals: [],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["freelancer", "freelance", "independent-contractor", "gig-worker", "1099", "self-employed", "solopreneur", "side-hustle", "contract-work"],
  },
  {
    id: "solo-consultant",
    name: "Independent Consultant",
    sector: "solopreneur",
    size: ["solo", "small"],
    description: "Independent consultant providing professional advisory services to clients",
    departments: [
      { domain: "General", name: "Practice Management", capabilities: ["client-engagements", "project-management", "deliverables", "scheduling"] },
      { domain: "Finance", name: "Finance", capabilities: ["invoicing", "contracts", "tax-planning", "expense-tracking", "budgeting"] },
      { domain: "Marketing", name: "Business Development", capabilities: ["networking", "proposals", "thought-leadership", "referrals", "branding"] },
    ],
    governance: {
      compliance: ["professional liability"],
      riskSignals: ["TRADE_SECRET"],
      additionalDomains: [],
      hitlDefaults: { "client-deliverables": "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["consultant", "consulting", "advisory", "independent-consultant", "management-consultant", "strategy-consultant", "professional-services", "boutique-consulting"],
  },
  {
    id: "solo-creator",
    name: "Content Creator / Influencer",
    sector: "solopreneur",
    size: ["solo", "small"],
    description: "Content creator or influencer producing digital content and managing brand partnerships",
    departments: [
      { domain: "Marketing", name: "Content & Growth", capabilities: ["content-creation", "audience-growth", "platform-management", "analytics", "brand-deals"] },
      { domain: "Finance", name: "Finance", capabilities: ["sponsorship-tracking", "tax-preparation", "invoicing", "expense-management"] },
      { domain: "Comms", name: "Community", capabilities: ["audience-engagement", "comments-moderation", "newsletters", "fan-interaction"] },
    ],
    governance: {
      compliance: ["FTC sponsored content guidelines", "COPPA", "platform terms of service"],
      riskSignals: ["PII"],
      additionalDomains: ["Marketing"],
      hitlDefaults: { "sponsored-content": "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["content-creator", "influencer", "YouTuber", "streamer", "blogger", "podcaster", "social-media-creator", "vlogger", "digital-creator", "creator-economy"],
  },
];
