module.exports = [
  {
    id: "tech-saas",
    name: "SaaS/Software Company",
    sector: "technology",
    size: ["small", "medium", "large"],
    description: "SaaS or software product company with engineering-driven operations",
    departments: [
      { domain: "Engineering", name: "Engineering", capabilities: ["backend", "frontend", "mobile", "architecture", "code-review", "testing"] },
      { domain: "Product", name: "Product", capabilities: ["product-management", "roadmap", "ux-research", "design", "analytics", "prioritization"] },
      { domain: "DevOps", name: "DevOps / Infrastructure", capabilities: ["ci-cd", "cloud-infrastructure", "monitoring", "security", "reliability", "incident-response"] },
      { domain: "CustomerSuccess", name: "Customer Success", capabilities: ["onboarding", "support", "account-management", "renewals", "health-scoring"] },
      { domain: "Sales", name: "Sales", capabilities: ["prospecting", "demos", "negotiation", "closing", "partnerships", "channel"] },
      { domain: "Marketing", name: "Marketing", capabilities: ["content", "demand-gen", "seo-sem", "product-marketing", "events", "brand"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "culture", "performance", "diversity"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "revenue-recognition", "budgeting", "fundraising", "tax", "payroll"] },
    ],
    governance: {
      compliance: ["SOC 2", "GDPR", "CCPA", "WCAG"],
      riskSignals: ["TRADE_SECRET", "PII"],
      additionalDomains: ["Technology", "DataPrivacy"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["SaaS", "software company", "software", "tech company", "cloud software", "platform", "B2B software", "B2C software", "app", "startup", "software product"],
  },
  {
    id: "tech-services",
    name: "IT Services/MSP",
    sector: "technology",
    size: ["small", "medium"],
    description: "IT services provider or managed service provider (MSP)",
    departments: [
      { domain: "ServiceDesk", name: "Service Desk", capabilities: ["helpdesk", "ticketing", "remote-support", "escalation", "knowledge-base"] },
      { domain: "Engineering", name: "Engineering", capabilities: ["network", "server", "cloud", "security", "migrations", "implementations"] },
      { domain: "Operations", name: "Operations", capabilities: ["monitoring", "patch-management", "backup", "disaster-recovery", "vendor-management"] },
      { domain: "Sales", name: "Sales", capabilities: ["prospecting", "proposals", "account-management", "renewals", "solution-design"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "mrr-tracking", "bookkeeping", "payroll", "vendor-payments"] },
    ],
    governance: {
      compliance: ["Client SLAs", "SOC 2", "HIPAA BAA", "PCI-DSS"],
      riskSignals: ["TRADE_SECRET", "PII"],
      additionalDomains: ["Technology", "ManagedServices"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: ["client-credential-sharing"],
    },
    discoveryKeywords: ["IT services", "MSP", "managed services", "managed service provider", "IT support", "IT company", "tech support", "IT consulting", "helpdesk", "network services"],
  },
  {
    id: "tech-agency",
    name: "Software Development Agency",
    sector: "technology",
    size: ["small", "medium"],
    description: "Custom software development or digital agency building solutions for clients",
    departments: [
      { domain: "Engineering", name: "Engineering", capabilities: ["backend", "frontend", "mobile", "devops", "qa", "architecture"] },
      { domain: "Design", name: "Design", capabilities: ["ui-design", "ux-research", "prototyping", "brand-design", "design-systems"] },
      { domain: "ProjectMgmt", name: "Project Management", capabilities: ["scrum", "client-coordination", "timelines", "resource-allocation", "reporting"] },
      { domain: "BusinessDev", name: "Business Development", capabilities: ["proposals", "client-acquisition", "partnerships", "account-management"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "project-accounting", "bookkeeping", "payroll", "budgeting"] },
    ],
    governance: {
      compliance: ["Client NDAs", "IP Assignment", "Data Protection"],
      riskSignals: ["TRADE_SECRET"],
      additionalDomains: ["Technology", "ProfessionalServices"],
      hitlDefaults: { ProjectMgmt: "DRAFT" },
      localOnlyDomains: [],
      prohibitedTopics: ["client-ip-disclosure"],
    },
    discoveryKeywords: ["software agency", "dev agency", "development agency", "digital agency", "web development", "app development", "custom software", "software house", "dev shop", "consultancy"],
  },
  {
    id: "tech-startup",
    name: "Tech Startup",
    sector: "technology",
    size: ["solo", "small", "medium"],
    description: "Early-stage or growth-stage technology startup with lean operations",
    departments: [
      { domain: "Engineering", name: "Engineering", capabilities: ["fullstack", "mvp", "iteration", "devops", "prototyping"] },
      { domain: "Product", name: "Product", capabilities: ["product-management", "user-research", "roadmap", "metrics", "experimentation"] },
      { domain: "Growth", name: "Growth", capabilities: ["acquisition", "activation", "retention", "referral", "revenue", "analytics"] },
      { domain: "Finance", name: "Finance", capabilities: ["bookkeeping", "fundraising", "runway-management", "cap-table", "tax"] },
    ],
    governance: {
      compliance: [],
      riskSignals: ["TRADE_SECRET"],
      additionalDomains: ["Technology"],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["startup", "tech startup", "early stage", "seed stage", "pre-seed", "series A", "venture-backed", "bootstrap", "founder", "MVP", "lean startup"],
  },
  {
    id: "tech-cybersecurity",
    name: "Cybersecurity Firm",
    sector: "technology",
    size: ["small", "medium", "large"],
    description: "Cybersecurity company providing security products or services",
    departments: [
      { domain: "SecurityOps", name: "Security Operations", capabilities: ["soc", "incident-response", "threat-intelligence", "monitoring", "forensics", "penetration-testing"] },
      { domain: "Consulting", name: "Consulting", capabilities: ["risk-assessment", "compliance-consulting", "vciso", "security-architecture", "training"] },
      { domain: "Engineering", name: "Engineering", capabilities: ["product-development", "detection-engineering", "tool-development", "research"] },
      { domain: "Sales", name: "Sales", capabilities: ["prospecting", "solution-selling", "channel-partnerships", "account-management"] },
      { domain: "HR", name: "Human Resources", capabilities: ["recruitment", "benefits", "clearance-support", "certification-tracking"] },
      { domain: "Finance", name: "Finance", capabilities: ["billing", "bookkeeping", "budgeting", "payroll"] },
    ],
    governance: {
      compliance: ["NIST CSF", "SOC 2", "ISO 27001"],
      riskSignals: ["TRADE_SECRET"],
      additionalDomains: ["Technology", "Cybersecurity"],
      hitlDefaults: { SecurityOps: "ESCALATE" },
      localOnlyDomains: ["Cybersecurity"],
      prohibitedTopics: ["client-vulnerability-disclosure", "exploit-sharing"],
    },
    discoveryKeywords: ["cybersecurity", "infosec", "information security", "security firm", "penetration testing", "SOC", "MSSP", "security consulting", "threat intelligence", "security operations"],
  },
];
