module.exports = [
  {
    id: "transport-freight",
    name: "Trucking / Freight",
    sector: "transportation",
    size: ["small", "medium", "large"],
    description: "Trucking company or freight carrier managing drivers, loads, and DOT compliance",
    departments: [
      { domain: "General", name: "Dispatch", capabilities: ["load-assignment", "route-planning", "driver-communication", "tracking"] },
      { domain: "General", name: "Operations", capabilities: ["fleet-scheduling", "load-management", "capacity-planning", "logistics"] },
      { domain: "General", name: "Safety", capabilities: ["driver-training", "incident-investigation", "inspections", "CSA-scores"] },
      { domain: "Legal", name: "Compliance", capabilities: ["DOT-reporting", "HOS-monitoring", "licensing", "audit-preparation"] },
      { domain: "General", name: "Maintenance", capabilities: ["preventive-maintenance", "repairs", "parts-inventory", "inspections"] },
      { domain: "HR", name: "Human Resources", capabilities: ["driver-recruitment", "CDL-verification", "benefits", "retention"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "invoicing", "fuel-management", "payroll", "IFTA-reporting"] },
    ],
    governance: {
      compliance: ["FMCSA", "DOT", "hours-of-service", "hazmat regulations"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: ["Safety", "Operations"],
      hitlDefaults: { "accidents": "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["trucking", "freight", "carrier", "logistics", "CDL", "DOT", "shipping", "hauling", "over-the-road", "LTL"],
  },
  {
    id: "transport-logistics",
    name: "Logistics / Warehousing",
    sector: "transportation",
    size: ["medium", "large", "enterprise"],
    description: "Logistics provider or warehouse operator managing supply chain and distribution",
    departments: [
      { domain: "General", name: "Warehouse", capabilities: ["receiving", "storage", "picking-packing", "inventory-management"] },
      { domain: "General", name: "Distribution", capabilities: ["shipping", "route-optimization", "last-mile", "tracking"] },
      { domain: "General", name: "Operations", capabilities: ["process-optimization", "capacity-planning", "vendor-management", "quality-control"] },
      { domain: "Legal", name: "Compliance", capabilities: ["customs", "hazmat", "import-export", "documentation"] },
      { domain: "IT", name: "IT", capabilities: ["WMS", "TMS", "integrations", "automation", "data-analytics"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "training", "safety-programs", "benefits"] },
      { domain: "Finance", name: "Finance", capabilities: ["accounting", "invoicing", "cost-analysis", "budgeting"] },
    ],
    governance: {
      compliance: ["OSHA", "customs regulations", "hazmat handling"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["logistics", "warehousing", "supply-chain", "distribution", "3PL", "fulfillment", "warehouse", "inventory", "cold-chain", "freight-forwarding"],
  },
  {
    id: "transport-transit",
    name: "Public Transit",
    sector: "transportation",
    size: ["large", "enterprise"],
    description: "Public transit authority or agency operating bus, rail, or multimodal transportation",
    departments: [
      { domain: "General", name: "Operations", capabilities: ["scheduling", "dispatching", "route-management", "fleet-operations"] },
      { domain: "General", name: "Planning", capabilities: ["route-planning", "ridership-analysis", "service-design", "capital-projects"] },
      { domain: "General", name: "Safety", capabilities: ["incident-investigation", "training", "inspections", "emergency-response"] },
      { domain: "General", name: "Customer Service", capabilities: ["rider-support", "complaints", "information", "accessibility"] },
      { domain: "HR", name: "Human Resources", capabilities: ["hiring", "labor-relations", "training", "benefits"] },
      { domain: "Finance", name: "Finance", capabilities: ["budgeting", "fare-revenue", "grants", "procurement", "reporting"] },
      { domain: "Legal", name: "Compliance", capabilities: ["FTA-reporting", "ADA-compliance", "FOIA", "safety-regulations"] },
    ],
    governance: {
      compliance: ["FTA", "ADA", "FOIA", "labor regulations"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: [],
      hitlDefaults: { "service-disruptions": "ESCALATE" },
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["public-transit", "transit-authority", "bus", "rail", "metro", "subway", "light-rail", "commuter", "paratransit", "transportation-agency"],
  },
  {
    id: "transport-fleet",
    name: "Fleet Management",
    sector: "transportation",
    size: ["small", "medium", "large"],
    description: "Fleet management operation overseeing vehicle maintenance, compliance, and driver safety",
    departments: [
      { domain: "General", name: "Fleet Operations", capabilities: ["vehicle-assignment", "scheduling", "utilization-tracking", "telematics"] },
      { domain: "General", name: "Maintenance", capabilities: ["preventive-maintenance", "repairs", "parts-inventory", "vendor-management"] },
      { domain: "General", name: "Safety", capabilities: ["driver-training", "incident-reporting", "inspections", "risk-assessment"] },
      { domain: "Legal", name: "Compliance", capabilities: ["DOT-reporting", "licensing", "insurance", "regulatory-tracking"] },
      { domain: "Finance", name: "Finance", capabilities: ["TCO-analysis", "budgeting", "fuel-management", "accounting"] },
    ],
    governance: {
      compliance: ["DOT", "FMCSA", "OSHA"],
      riskSignals: ["SAFETY_INCIDENT"],
      additionalDomains: [],
      hitlDefaults: {},
      localOnlyDomains: [],
      prohibitedTopics: [],
    },
    discoveryKeywords: ["fleet-management", "fleet", "vehicle-management", "telematics", "fleet-tracking", "fleet-maintenance", "motor-pool", "vehicle-fleet"],
  },
];
